# Generated by Django 4.2.11 on 2024-05-07 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='level',
            field=models.IntegerField(choices=[(0, 'READ_ONLY'), (1, 'READ_AND_WRITE'), (2, 'OWNER')], default=0, verbose_name='level'),
        ),
    ]
