# Generated by Django 5.2.4 on 2025-08-08 21:45

import django.db.models.deletion
import speleodb.utils.storages
import speleodb.utils.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0002_add_stationresource_miniature'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='stationresource',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_station_resources', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='stationresource',
            name='file',
            field=models.FileField(blank=True, null=True, storage=speleodb.utils.storages.StationResourceStorage(), upload_to='stations/resources/%Y/%m/%d/', validators=[speleodb.utils.validators.StationResourceFileValidator()]),
        ),
        migrations.AlterField(
            model_name='stationresource',
            name='text_content',
            field=models.TextField(blank=True, default='', help_text='Text content for notes or sketch descriptions'),
        ),
    ]
