# Generated by Django 5.2.4 on 2025-08-11 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0003_alter_stationresource_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='format',
            name='creation_date',
            field=models.DateTimeField(),
        ),
    ]
