# Generated by Django 5.2.5 on 2025-08-14 02:52

import django.core.validators
import django.db.models.deletion
import speleodb.surveys.models.geojson
import speleodb.utils.storages
import speleodb.utils.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0004_alter_format_creation_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='geojson',
        ),
        migrations.CreateModel(
            name='GeoJSON',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(storage=speleodb.utils.storages.GeoJSONStorage(), upload_to=speleodb.surveys.models.geojson.get_geojson_upload_path, validators=[speleodb.utils.validators.GeoJsonValidator()])),
                ('commit_sha', models.CharField(max_length=40, unique=True, validators=[django.core.validators.RegexValidator(message='Enter a valid sha1 value', regex='^[0-9a-f]{40}$')])),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rel_geojson', to='surveys.project')),
            ],
            options={
                'verbose_name': 'GeoJSON',
                'verbose_name_plural': 'GeoJSONs',
            },
        ),
    ]
