# Generated by Django 5.2.5 on 2025-08-18 23:02

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0005_remove_project_geojson_geojson'),
    ]

    operations = [
        migrations.AddField(
            model_name='geojson',
            name='commit_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='geojson',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rel_geojsons', to='surveys.project'),
        ),
    ]
