# Generated by Django 5.0.6 on 2024-06-06 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0005_remove_project_mutex_dt_remove_project_mutex_owner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='software',
            field=models.IntegerField(choices=[(0, 'MANUAL'), (1, 'ARIANE'), (2, 'COMPASS'), (3, 'WALLS'), (4, 'STICKMAPS'), (99, 'OTHER')], default=1, verbose_name='software'),
            preserve_default=False,
        ),
    ]
