# Generated by Django 5.2.5 on 2025-08-21 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0006_geojson_commit_date_alter_geojson_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='exclude_geojson',
            field=models.BooleanField(default=False, help_text='Exclude GeoJSON from the project'),
        ),
    ]
