# Generated by Django 5.2.7 on 2025-10-14 19:29

import speleodb.gis.models.station
import speleodb.utils.storages
import speleodb.utils.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0007_project_exclude_geojson'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stationresource',
            name='file',
            field=models.FileField(blank=True, null=True, storage=speleodb.utils.storages.AttachmentStorage(), upload_to=speleodb.gis.models.station.get_station_resource_path, validators=[speleodb.utils.validators.AttachmentValidator()]),
        ),
        migrations.AlterField(
            model_name='stationresource',
            name='miniature',
            field=models.ImageField(blank=True, help_text='Thumbnail/preview image for the resource', null=True, storage=speleodb.utils.storages.AttachmentStorage(), upload_to=speleodb.gis.models.station.get_station_resource_path),
        ),
    ]
