# Generated by Django 5.0.6 on 2024-06-11 04:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0007_rename_level_permission__level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='permission',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='permission',
            name='modified_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
