# Generated by Django 5.2.7 on 2025-10-18 04:04

import django.db.models.deletion
import speleodb.gis.models.log_entry
import speleodb.utils.storages
import speleodb.utils.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0009_alter_project_created_by_alter_station_created_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StationLogEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_by', models.EmailField(help_text='User who created or submitted the entry.', max_length=254)),
                ('title', models.CharField(help_text='Short title or summary of the observation.', max_length=255)),
                ('notes', models.TextField(blank=True, help_text='Detailed field notes, observations, or measurements.')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('attachment', models.FileField(blank=True, help_text='Any relevant file (sketch, lab sheet, sensor data, etc.).', null=True, storage=speleodb.utils.storages.AttachmentStorage(), upload_to=speleodb.gis.models.log_entry.get_log_entry_path, validators=[speleodb.utils.validators.AttachmentValidator()])),
                ('station', models.ForeignKey(help_text='The station or location this log entry is associated with.', on_delete=django.db.models.deletion.CASCADE, related_name='log_entries', to='surveys.station')),
            ],
            options={
                'verbose_name_plural': 'Log Entries',
                'ordering': ['-creation_date'],
            },
        ),
    ]
