# Generated by Django 5.0.6 on 2024-06-12 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0009_rename_heartbeat_dt_mutex_last_modified_dt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='_level',
            field=models.IntegerField(choices=[(0, 'READ_ONLY'), (1, 'READ_AND_WRITE'), (2, 'ADMIN')], default=0, verbose_name='level'),
        ),
    ]
