# Generated by Django 5.2.7 on 2025-10-18 04:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0010_logentry'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='pointofinterest',
            name='surveys_poi_created_7c3dcc_idx',
        ),
        migrations.RenameField(
            model_name='pointofinterest',
            old_name='created_by',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='pointofinterest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pois', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='pointofinterest',
            index=models.Index(fields=['user'], name='surveys_poi_user_id_4185ea_idx'),
        ),
    ]
