# Generated by Django 5.2.7 on 2025-10-18 22:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0011_remove_pointofinterest_surveys_poi_created_7c3dcc_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stationresource',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='surveys.station'),
        ),
    ]
