# Generated by Django 5.2.8 on 2025-11-08 05:58

import speleodb.surveys.models.station
import speleodb.utils.storages
import speleodb.utils.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0012_alter_stationresource_station'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stationresource',
            name='file',
            field=models.FileField(blank=True, max_length=255, null=True, storage=speleodb.utils.storages.AttachmentStorage(), upload_to=speleodb.surveys.models.station.get_station_resource_path, validators=[speleodb.utils.validators.AttachmentValidator()]),
        ),
        migrations.AlterField(
            model_name='stationresource',
            name='miniature',
            field=models.ImageField(blank=True, help_text='Thumbnail/preview image for the resource', max_length=255, null=True, storage=speleodb.utils.storages.AttachmentStorage(), upload_to=speleodb.surveys.models.station.get_station_resource_path),
        ),
    ]
