# Generated by Django 5.0.6 on 2024-06-22 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0013_remove_project__software_format'),
    ]

    operations = [
        migrations.AlterField(
            model_name='format',
            name='_format',
            field=models.IntegerField(choices=[(1000, 'OTHER'), (10, 'ARIANE_TML'), (11, 'ARIANE_TMLU'), (12, 'ARIANE_AGR'), (20, 'COMPASS_MAK'), (21, 'COMPASS_DAT'), (30, 'WALLS_SRV'), (31, 'WALLS_WPJ'), (40, 'STICKMAPS')], verbose_name='format'),
        ),
    ]
