# Generated by Django 5.2.8 on 2025-11-17 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0014_project_is_active'),
    ]

    operations = [
        # ============= Plugin:PluginRelease ============= #
        migrations.RenameModel(
            old_name='PluginRelease',
            new_name='__temp_pluginrelease__',
        ),
        migrations.AlterModelTable(
            name='__temp_pluginrelease__',
            table='plugins_pluginrelease',
        ),

        # ============= Plugin:PublicAnnoucement ============= #
        migrations.RenameModel(
            old_name='PublicAnnoucement',
            new_name='__temp_publicannouncement__',
        ),
        migrations.AlterModelTable(
            name='__temp_publicannouncement__',
            table='plugins_publicannoucement',
        ),
        
        # ============= GIS:GeoJSON ============= #
        migrations.RenameModel(
            old_name='GeoJSON',
            new_name='__temp_geojson__',
        ),
        migrations.AlterModelTable(
            name='__temp_geojson__',
            table='gis_geojson',
        ),
        
        # ============= GIS:PointOfInterest ============= #
        migrations.RenameModel(
            old_name='PointOfInterest',
            new_name='__temp_pointofinterest__',
        ),
        migrations.AlterModelTable(
            name='__temp_pointofinterest__',
            table='gis_pointofinterest',
        ),
    ]
