# Generated by Django 5.1.3 on 2024-12-06 20:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0015_alter_format__format'),
        ('users', '0002_surveyteam_surveyteammembership'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('_level', models.IntegerField(choices=[(0, 'READ_ONLY'), (1, 'READ_AND_WRITE')], default=0, verbose_name='level')),
                ('deactivated_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rel_team_permissions', to='surveys.project')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rel_permissions', to='users.surveyteam')),
            ],
            options={
                'verbose_name': 'Team Permission',
                'verbose_name_plural': 'Team Permissions',
                'abstract': False,
                'unique_together': {('target', 'project')},
            },
        ),
        migrations.CreateModel(
            name='UserPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('_level', models.IntegerField(choices=[(0, 'Read Only'), (1, 'Read And Write'), (2, 'ADMIN')], default=0, verbose_name='level')),
                ('deactivated_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rel_user_permissions', to='surveys.project')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rel_permissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Permission',
                'verbose_name_plural': 'User Permissions',
                'abstract': False,
                'unique_together': {('target', 'project')},
            },
        ),
        migrations.DeleteModel(
            name='Permission',
        ),
    ]
