# Generated by Django 5.2.8 on 2025-11-17 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0015_model_redispatch'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveField(
                    model_name='__temp_geojson__',
                    name='project',
                ),
                migrations.DeleteModel(
                    name='__temp_pluginrelease__',
                ),
                migrations.RemoveField(
                    model_name='__temp_pointofinterest__',
                    name='user',
                ),
                migrations.DeleteModel(
                    name='__temp_publicannouncement__',
                ),
                migrations.DeleteModel(
                    name='__temp_geojson__',
                ),
                migrations.DeleteModel(
                    name='__temp_pointofinterest__',
                ),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='station',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='station',
            name='project',
        ),
        migrations.RemoveField(
            model_name='stationresource',
            name='station',
        ),
        migrations.DeleteModel(
            name='StationLogEntry',
        ),
        migrations.DeleteModel(
            name='Station',
        ),
        migrations.DeleteModel(
            name='StationResource',
        ),
    ]
