# Generated by Django 5.2.8 on 2025-11-17 17:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0016_finalize_transfer'),
        ('users', '0002_user_is_beta_tester'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Mutex',
            new_name='ProjectMutex',
        ),
        migrations.RenameModel(
            old_name='TeamPermission',
            new_name='TeamProjectPermission',
        ),
        migrations.RenameModel(
            old_name='UserPermission',
            new_name='UserProjectPermission',
        ),
        migrations.RemoveConstraint(
            model_name='teamprojectpermission',
            name='surveys_teampermission_level_is_valid',
        ),
        migrations.AddConstraint(
            model_name='teamprojectpermission',
            constraint=models.CheckConstraint(condition=models.Q(('level__in', [0, 1, 2])), name='surveys_teamprojectpermission_level_is_valid'),
        ),
    ]
