# Generated by Django 5.2.8 on 2025-11-17 17:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0017_rename_mutex_projectmutex_and_more'),
        ('users', '0002_user_is_beta_tester'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teamprojectpermission',
            options={'verbose_name': 'Project - Team Permission', 'verbose_name_plural': 'Project - Team Permissions'},
        ),
        migrations.AlterModelOptions(
            name='userprojectpermission',
            options={'verbose_name': 'Project - User Permission', 'verbose_name_plural': 'Project - User Permissions'},
        ),
        migrations.AddIndex(
            model_name='teamprojectpermission',
            index=models.Index(fields=['target', 'is_active'], name='surveys_tea_target__854ce7_idx'),
        ),
        migrations.AddIndex(
            model_name='teamprojectpermission',
            index=models.Index(fields=['project', 'is_active'], name='surveys_tea_project_a00b77_idx'),
        ),
        migrations.AddIndex(
            model_name='teamprojectpermission',
            index=models.Index(fields=['target', 'project', 'is_active'], name='surveys_tea_target__fdb1c2_idx'),
        ),
        migrations.AddIndex(
            model_name='userprojectpermission',
            index=models.Index(fields=['target', 'is_active'], name='surveys_use_target__303642_idx'),
        ),
        migrations.AddIndex(
            model_name='userprojectpermission',
            index=models.Index(fields=['project', 'is_active'], name='surveys_use_project_f7ca9a_idx'),
        ),
        migrations.AddIndex(
            model_name='userprojectpermission',
            index=models.Index(fields=['target', 'project', 'is_active'], name='surveys_use_target__d5ed5f_idx'),
        ),
    ]
