# Generated by Django 5.2.8 on 2025-11-23 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0018_project_permissions_indexes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='format',
            name='_format',
            field=models.IntegerField(choices=[(1000, 'OTHER'), (9998, 'AUTO'), (9999, 'DUMP'), (10, 'ARIANE_TML'), (11, 'ARIANE_TMLU'), (12, 'ARIANE_AGR'), (20, 'COMPASS_ZIP'), (21, 'COMPASS_MANUAL'), (30, 'WALLS_SRV'), (31, 'WALLS_WPJ'), (40, 'STICKMAPS')], verbose_name='format'),
        ),
    ]
