# Generated by Django 5.2.8 on 2025-12-01 04:12

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0019_alter_format__format'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectCommit',
            fields=[
                ('oid', models.CharField(help_text='Specific commit SHA (40 hex chars).', max_length=40, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(message='Enter a valid sha1 value', regex='^[0-9a-f]{40}$')])),
                ('parents', models.JSONField(default=list, help_text='List of parent hexsha strings.', validators=[django.core.validators.RegexValidator(message='Enter a valid list of sha1 values', regex='^([0-9a-f]{40},?)*$')])),
                ('author_name', models.CharField(max_length=255, verbose_name='Name of User')),
                ('author_email', models.EmailField(max_length=254, verbose_name='email address')),
                ('message', models.CharField(max_length=1024, verbose_name='commit message')),
                ('datetime', models.DateTimeField()),
                ('tree', models.JSONField(blank=True, default=dict, help_text='`git ls-tree -r` data.')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='commits', to='surveys.project')),
            ],
            options={
                'verbose_name': 'Project Commit',
                'verbose_name_plural': 'Project Commits',
                'ordering': ('-datetime',),
                'indexes': [models.Index(fields=['project'], name='surveys_pro_project_183435_idx'), models.Index(fields=['project', 'datetime'], name='surveys_pro_project_35d638_idx')],
            },
        ),
    ]
