# Generated by Django 5.2.8 on 2025-12-01 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0020_projectcommit'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='type',
            field=models.CharField(
                choices=[
                    ('ariane', 'ARIANE'), 
                    ('compass', 'COMPASS'), 
                    ('stickmaps', 'STICKMAPS'), 
                    ('therion', 'THERION'), 
                    ('walls', 'WALLS'), 
                    ('other', 'OTHER')
                ], 
                default='ariane', 
                max_length=20
            ),
            preserve_default=False,
        ),
    ]
