# Generated by Django 5.1.8 on 2025-05-25 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0021_alter_mutex_closing_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teampermission',
            name='_level',
        ),
        migrations.RemoveField(
            model_name='userpermission',
            name='_level',
        ),
        migrations.AddField(
            model_name='teampermission',
            name='level',
            field=models.IntegerField(choices=[(0, 'READ_ONLY'), (1, 'READ_AND_WRITE')], default=0),
        ),
        migrations.AddField(
            model_name='userpermission',
            name='level',
            field=models.IntegerField(choices=[(0, 'READ_ONLY'), (1, 'READ_AND_WRITE'), (2, 'ADMIN')], default=0),
        ),
    ]
