# Generated by Django 5.2.8 on 2025-12-01 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0021_project_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectcommit',
            options={'ordering': ('-authored_date',), 'verbose_name': 'Project Commit', 'verbose_name_plural': 'Project Commits'},
        ),
        migrations.RemoveIndex(
            model_name='projectcommit',
            name='surveys_pro_project_35d638_idx',
        ),
        migrations.RenameField(
            model_name='projectcommit',
            old_name='oid',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='projectcommit',
            old_name='parents',
            new_name='parent_ids',
        ),
        migrations.RenameField(
            model_name='projectcommit',
            old_name='datetime',
            new_name='authored_date',
        ),        
        migrations.AlterField(
            model_name='projectcommit',
            name='authored_date',
            field=models.DateTimeField(help_text='Date and time when the commit was authored.'),
        ),
        migrations.AddIndex(
            model_name='projectcommit',
            index=models.Index(fields=['project', 'authored_date'], name='surveys_pro_project_aeece0_idx'),
        ),
       
    ]
