# Generated by Django 5.2.3 on 2025-06-23 05:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0021_remove_teampermission__level_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicAnnoucement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('header', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('software', models.IntegerField(choices=[(0, 'WEB'), (1, 'ARIANE')])),
                ('_version', models.CharField(blank=True, default='', max_length=50, validators=[django.core.validators.RegexValidator(message='Enter a valid SemVer (e.g., 1.2.3) or CalVer (e.g., 2025.06)', regex='(^(?P<major>0|[1-9]\\d*)\\.(?P<minor>0|[1-9]\\d*)\\.(?P<patch>0|[1-9]\\d*)$)|(^(?P<year>2[0-9]{3}).(?P<month>1[0-2]|0?[1-9]).(?P<day>3[0-1]|[1-2][0-9]|0?[1-9])$)')])),
                ('is_active', models.BooleanField(default=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('expiracy_date', models.DateField(blank=True, default=None, null=True)),
            ],
        ),
    ]
