# Generated by Django 5.2.8 on 2025-12-02 02:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0022_adjust_projectcommit'),
        ('users', '0003_index_optimizations'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='teamprojectpermission',
            name='surveys_tea_target__854ce7_idx',
        ),
        migrations.RemoveIndex(
            model_name='teamprojectpermission',
            name='surveys_tea_project_a00b77_idx',
        ),
        migrations.RemoveIndex(
            model_name='teamprojectpermission',
            name='surveys_tea_target__fdb1c2_idx',
        ),
        migrations.RemoveIndex(
            model_name='userprojectpermission',
            name='surveys_use_target__303642_idx',
        ),
        migrations.RemoveIndex(
            model_name='userprojectpermission',
            name='surveys_use_project_f7ca9a_idx',
        ),
        migrations.RemoveIndex(
            model_name='userprojectpermission',
            name='surveys_use_target__d5ed5f_idx',
        ),
        migrations.AddIndex(
            model_name='format',
            index=models.Index(fields=['project'], name='surveys_for_project_e20806_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['country'], name='surveys_pro_country_8576c3_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['is_active'], name='surveys_pro_is_acti_0cd226_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['longitude', 'latitude'], name='surveys_pro_longitu_673a65_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['visibility'], name='surveys_pro_visibil_f4076e_idx'),
        ),
        migrations.AddIndex(
            model_name='projectmutex',
            index=models.Index(fields=['project'], name='surveys_pro_project_e3b9ce_idx'),
        ),
        migrations.AddIndex(
            model_name='projectmutex',
            index=models.Index(fields=['project', 'user'], name='surveys_pro_project_5c9bd9_idx'),
        ),
        migrations.AddIndex(
            model_name='teamprojectpermission',
            index=models.Index(fields=['target'], name='surveys_tea_target__bf483a_idx'),
        ),
        migrations.AddIndex(
            model_name='teamprojectpermission',
            index=models.Index(fields=['project'], name='surveys_tea_project_516aaa_idx'),
        ),
        migrations.AddIndex(
            model_name='userprojectpermission',
            index=models.Index(fields=['target'], name='surveys_use_target__34ed31_idx'),
        ),
        migrations.AddIndex(
            model_name='userprojectpermission',
            index=models.Index(fields=['project'], name='surveys_use_project_d1e670_idx'),
        ),
    ]
