# Generated by Django 5.1.8 on 2025-05-25 19:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0022_remove_teampermission__level_and_more'),
        ('users', '0003_alter_surveyteam_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='teampermission',
            name='deactivated_by',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='teampermission',
            name='level',
            field=models.IntegerField(choices=[(0, 'Read Only'), (1, 'Read And Write'), (2, 'Admin')], default=0),
        ),
        migrations.AlterField(
            model_name='userpermission',
            name='deactivated_by',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userpermission',
            name='level',
            field=models.IntegerField(choices=[(0, 'Read Only'), (1, 'Read And Write'), (2, 'Admin')], default=0),
        ),
        migrations.AddConstraint(
            model_name='teampermission',
            constraint=models.CheckConstraint(condition=models.Q(('level__in', [0, 1])), name='surveys_teampermission_level_is_valid'),
        ),
    ]
