# Generated by Django 5.2.9 on 2025-12-06 19:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0023_index_optimizations'),
        ('users', '0004_related_fields_rename'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='format',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='_formats', to='surveys.project'),
        ),
        migrations.AlterField(
            model_name='projectmutex',
            name='closing_user',
            field=models.ForeignKey(
                blank=True, 
                default=None, 
                null=True, 
                on_delete=django.db.models.deletion.RESTRICT, 
                related_name='closing_mutexes', 
                to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name='projectmutex',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mutexes', to='surveys.project'),
        ),
        migrations.AlterField(
            model_name='projectmutex',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mutexes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='teamprojectpermission',
            name='project',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, 
                related_name='_team_permissions', 
                to='surveys.project'
            ),
        ),
        migrations.AlterField(
            model_name='teamprojectpermission',
            name='target',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, 
                related_name='project_permissions', 
                to='users.surveyteam'
            ),
        ),
        migrations.AlterField(
            model_name='userprojectpermission',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='_user_permissions', to='surveys.project'),
        ),
        migrations.AlterField(
            model_name='userprojectpermission',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_user_permissions', to=settings.AUTH_USER_MODEL),
        ),
    ]
