# Generated by Django 6.0.1 on 2026-01-15 03:35

from django.conf import settings
from django.db import migrations, models


def copy_user_email(apps, schema_editor):
    ProjectMutex = apps.get_model('surveys', 'ProjectMutex')
    User = apps.get_model('users', 'User')

    for obj in ProjectMutex.objects.all():
        # Check if FK exists if not pass
        if getattr(obj, "closing_user_id", None) is None:
            obj.closing_user_email = ""

        else:
            # Check if the referenced User exists
            user = User.objects.filter(pk=obj.closing_user_id).first()
            if not user:
                raise ValueError(
                    f"Cannot migrate {ProjectMutex.__name__} id={obj.pk}: User with id={obj.closing_user_id} does not exist"
                )

            # Copy email
            obj.closing_user_email = user.email
            
        obj.save(update_fields=['closing_user_email'])


def copy_user_email_reverse(apps, schema_editor):
    ProjectMutex = apps.get_model('surveys', 'ProjectMutex')
    User = apps.get_model('users', 'User')

    for obj in ProjectMutex.objects.all():
        if obj.closing_user_email:  # this is now the email string
            user = User.objects.filter(email=obj.closing_user_email).first()
            if user:
                obj.closing_user_id = user.id
                obj.save(update_fields=['closing_user_id'])


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0024_related_fields_rename'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # 1. Add temporary field to hold emails (nullable at first)
        migrations.AddField(
            model_name='projectmutex',
            name='closing_user_email',
            field=models.EmailField(
                blank=True, 
                help_text='User who released the mutex.', 
                max_length=254,
                null=True
            ),
        ),

        # 2. Copy data from FK to email
        migrations.RunPython(
            copy_user_email,
            reverse_code=copy_user_email_reverse
        ),

        # 3. Ensure no NULLs remain before removing FK
        migrations.AlterField(
            model_name='projectmutex',
            name='closing_user_email',
            field=models.EmailField(
                blank=True, 
                help_text='User who released the mutex.', 
                max_length=254,
                null=False,
            ),
        ),

        # 4. Remove old FK field
        migrations.RemoveField(
            model_name='projectmutex',
            name='closing_user',
        ),

        # 5. Rename new email field to original name
        migrations.RenameField(
            model_name='projectmutex',
            old_name='closing_user_email',
            new_name='closing_user',
        ),
        # ==================== Adding Indexes =================== #
        migrations.AddIndex(
            model_name='projectmutex',
            index=models.Index(fields=['is_active'], name='surveys_pro_is_acti_f3517e_idx'),
        ),
        migrations.AddIndex(
            model_name='projectmutex',
            index=models.Index(fields=['user'], name='surveys_pro_user_id_6c89c4_idx'),
        ),
        migrations.AddIndex(
            model_name='projectmutex',
            index=models.Index(fields=['project', 'user', 'is_active'], name='surveys_pro_project_506716_idx'),
        ),
    ]
