# Generated by Django 6.0.1 on 2026-01-16 04:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0025_projectmutex_indexes'),
        ('users', '0005_unique_together_update'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='format',
            unique_together=set(),
        ),

        # Note: Problem with SQLite, this constraint must be removed first
        #       to allow the other one to pass. Will be recreated afterwards.
        migrations.RemoveConstraint(
            model_name='teamprojectpermission',
            name='surveys_teamprojectpermission_level_is_valid',
        ),
        migrations.AlterUniqueTogether(
            name='teamprojectpermission',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='userprojectpermission',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='format',
            constraint=models.UniqueConstraint(
                fields=('project', '_format'), 
                name='surveys_format_project_format_unique'
            ),
        ),
        
        migrations.AddConstraint(
            model_name='teamprojectpermission',
            constraint=models.CheckConstraint(
                condition=models.Q(('level__in', [0, 1, 2])), 
                name='surveys_teamprojectpermission_level_is_valid'
            ),
        ),
        migrations.AddConstraint(
            model_name='teamprojectpermission',
            constraint=models.UniqueConstraint(
                fields=('target', 'project'), 
                name='surveys_teamprojectpermission_team_project_unique'
            ),
        ),
        migrations.AddConstraint(
            model_name='userprojectpermission',
            constraint=models.UniqueConstraint(
                fields=('target', 'project'), 
                name='surveys_userprojectpermission_user_project_unique'
            ),
        ),
    ]
