# Generated by Django 5.2.3 on 2025-07-05 16:05

import django.core.validators
import django.db.models.deletion
import speleodb.utils.storages
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0027_alter_project_latitude_alter_project_longitude_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(help_text="Station identifier (e.g., 'A1', 'Station-001')", max_length=100)),
                ('description', models.TextField(blank=True, default='', help_text='Optional description of the station')),
                ('latitude', models.DecimalField(decimal_places=7, help_text='Station latitude coordinate', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('-90.0')), django.core.validators.MaxValueValidator(Decimal('90.0'))])),
                ('longitude', models.DecimalField(decimal_places=7, help_text='Station longitude coordinate', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('-180.0')), django.core.validators.MaxValueValidator(Decimal('180.0'))])),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stations_created', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stations', to='surveys.project')),
            ],
            options={
                'verbose_name': 'Station',
                'verbose_name_plural': 'Stations',
                'ordering': ['project', 'name'],
                'unique_together': {('project', 'name')},
            },
        ),
        migrations.CreateModel(
            name='StationResource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('resource_type', models.CharField(choices=[('photo', 'Photo'), ('video', 'Video'), ('sketch', 'Sketch'), ('note', 'Note'), ('document', 'Document')], max_length=20)),
                ('title', models.CharField(help_text='Title or name of the resource', max_length=200)),
                ('description', models.TextField(blank=True, default='', help_text='Optional description of the resource')),
                ('file', models.FileField(blank=True, null=True, storage=speleodb.utils.storages.StationResourceStorage(), upload_to='stations/resources/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'bmp', 'webp', 'mp4', 'avi', 'mov', 'wmv', 'flv', 'webm', 'pdf', 'doc', 'docx', 'txt', 'rtf', 'svg'])])),
                ('text_content', models.TextField(blank=True, default='', help_text='Text content for notes or sketch SVG data')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='station_resources_created', to=settings.AUTH_USER_MODEL)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='surveys.station')),
            ],
            options={
                'verbose_name': 'Station Resource',
                'verbose_name_plural': 'Station Resources',
                'ordering': ['station', '-modified_date'],
            },
        ),
        migrations.CreateModel(
            name='PointOfInterest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(help_text='Point of Interest name (must be unique)', max_length=100)),
                ('description', models.TextField(blank=True, default='', help_text='Optional description of the point of interest')),
                ('latitude', models.DecimalField(decimal_places=7, help_text='POI latitude coordinate', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('-90.0')), django.core.validators.MaxValueValidator(Decimal('90.0'))])),
                ('longitude', models.DecimalField(decimal_places=7, help_text='POI longitude coordinate', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('-180.0')), django.core.validators.MaxValueValidator(Decimal('180.0'))])),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pois_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Point of Interest',
                'verbose_name_plural': 'Points of Interest',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['latitude', 'longitude'], name='surveys_poi_latitud_22d2b1_idx'), models.Index(fields=['name'], name='surveys_poi_name_59f0fd_idx'), models.Index(fields=['creation_date'], name='surveys_poi_creatio_9acde1_idx')],
            },
        ),
    ]
