# Generated by Django 5.2.4 on 2025-07-10 18:30

import uuid
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0030_normalize_uuid_fields_accross_app'),
    ]

    operations = [
        # Step 1: Break unique constraint to allow changes
        migrations.AlterUniqueTogether(
            name='teampermission',
            unique_together=set(),
        ),

        # Step 2: Add temporary UUID field for target
        migrations.AddField(
            model_name='teampermission',
            name='target_uuid',
            field=models.UUIDField(null=True),
        ),
        
        # Step 3: Drop FK Constraint
        migrations.AlterField(
            model_name='teampermission',
            name='target',
            field=models.IntegerField(),
        )
    ]
