# Generated by Django 5.2.4 on 2025-07-10 22:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0032_migrate_teampermission_fk_to_uuid'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='rel_projects_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='station',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='rel_stations_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='stationresource',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='rel_station_resources_created', to=settings.AUTH_USER_MODEL),
        ),
    ]
