# Generated by Django 5.2.8 on 2025-11-17 05:17

import uuid

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import speleodb.gis.models.experiment
import speleodb.gis.models.project_geojson
import speleodb.gis.models.log_entry
import speleodb.gis.models.station
import speleodb.utils.storages
import speleodb.utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ('gis', '0001_initial'),
        ('surveys', '0015_model_redispatch'),
    ]

    operations = [

        # Move models from surveys app to plugin app
        # The database tables were already renamed to plugin_* in surveys migration 0015
        # We use SeparateDatabaseAndState because the tables already exist in the database
        migrations.SeparateDatabaseAndState(
            state_operations=[
                # Add models to plugin app state with final names
                # The tables already exist, so we're just updating Django's migration state[
                migrations.CreateModel(
                    name='GeoJSON',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('file', models.FileField(storage=speleodb.utils.storages.GeoJSONStorage(), upload_to=speleodb.gis.models.project_geojson.get_geojson_upload_path, validators=[speleodb.utils.validators.GeoJsonValidator()])),
                        ('commit_sha', models.CharField(max_length=40, unique=True, validators=[django.core.validators.RegexValidator(message='Enter a valid sha1 value', regex='^[0-9a-f]{40}$')])),
                        ('commit_date', models.DateTimeField()),
                        ('creation_date', models.DateTimeField(auto_now_add=True)),
                        ('modified_date', models.DateTimeField(auto_now=True)),
                        ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rel_geojsons', to='surveys.project')),
                    ],
                    options={
                        'verbose_name': 'GeoJSON',
                        'verbose_name_plural': 'GeoJSONs',
                    },
                ),
                migrations.CreateModel(
                    name='PointOfInterest',
                    fields=[
                        ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                        ('name', models.CharField(help_text='Point of Interest name', max_length=100)),
                        ('description', models.TextField(blank=True, default='', help_text='Optional description of the point of interest')),
                        ('latitude', models.DecimalField(decimal_places=7, help_text='POI latitude coordinate', max_digits=10, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)])),
                        ('longitude', models.DecimalField(decimal_places=7, help_text='POI longitude coordinate', max_digits=10, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)])),
                        ('creation_date', models.DateTimeField(auto_now_add=True)),
                        ('modified_date', models.DateTimeField(auto_now=True)),
                        ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pois', to=settings.AUTH_USER_MODEL)),
                    ],
                    options={
                        'verbose_name': 'Point of Interest',
                        'verbose_name_plural': 'Points of Interest',
                        'ordering': ['name'],
                        'indexes': [models.Index(fields=['latitude', 'longitude'], name='gis_pointof_latitud_35c73d_idx'), models.Index(fields=['name'], name='gis_pointof_name_51170f_idx'), models.Index(fields=['creation_date'], name='gis_pointof_creatio_9c576a_idx'), models.Index(fields=['user'], name='gis_pointof_user_id_81abda_idx')],
                    },
                ),
            ]
        )
    ]
