# Generated by Django 5.2.8 on 2025-11-17 15:38

import django.core.validators
import django.db.models.deletion
import speleodb.gis.models.utils
import speleodb.gis.models.log_entry
import speleodb.gis.models.station
import speleodb.utils.storages
import speleodb.utils.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gis', '0002_models_transfer'),
        ('surveys', '0016_finalize_transfer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experiment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(blank=True, help_text='Short project code, e.g. AQ-2025-GL', max_length=64)),
                ('name', models.CharField(help_text='Experiment name', max_length=255)),
                ('description', models.TextField(blank=True)),
                ('experiment_fields', models.JSONField(blank=True, default=dict, help_text="Field definitions for data collection at each station. Structure: {field_slug: {name, type, required, options}}. Mandatory fields are identified by their slug, not a 'mandatory' property.")),
                ('created_by', models.EmailField(help_text='User who created or submitted the entry.', max_length=254)),
                ('is_active', models.BooleanField(default=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('gis_token', models.CharField(default=speleodb.gis.models.utils.generate_random_token, max_length=40, unique=True, verbose_name='GIS Token')),
            ],
            options={
                'ordering': ['-creation_date'],
                'indexes': [models.Index(fields=['is_active'], name='gis_experim_is_acti_eb5f2b_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('end_date__isnull', True), ('start_date__isnull', False), _connector='OR'), name='end_date_requires_start_date'), models.CheckConstraint(condition=models.Q(('start_date__isnull', True), ('end_date__isnull', True), ('start_date__lte', models.F('end_date')), _connector='OR'), name='start_date_lte_end_date')],
            },
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="Station identifier (e.g., 'A1', 'Station-001')", max_length=100)),
                ('description', models.TextField(blank=True, default='', help_text='Optional description of the station')),
                ('latitude', models.DecimalField(decimal_places=7, help_text='Station latitude coordinate', max_digits=10, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)])),
                ('longitude', models.DecimalField(decimal_places=7, help_text='Station longitude coordinate', max_digits=10, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)])),
                ('created_by', models.EmailField(help_text='User who created or submitted the entry.', max_length=254)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rel_stations', to='surveys.project')),
            ],
            options={
                'verbose_name': 'Station',
                'verbose_name_plural': 'Stations',
                'ordering': ['project', 'name'],
                'unique_together': {('project', 'name')},
            },
        ),
        migrations.CreateModel(
            name='LogEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_by', models.EmailField(help_text='User who created or submitted the entry.', max_length=254)),
                ('title', models.CharField(help_text='Short title or summary of the observation.', max_length=255)),
                ('notes', models.TextField(blank=True, help_text='Detailed field notes, observations, or measurements.')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('attachment', models.FileField(blank=True, help_text='Any relevant file (sketch, lab sheet, sensor data, etc.).', null=True, storage=speleodb.utils.storages.AttachmentStorage(), upload_to=speleodb.gis.models.log_entry.get_log_entry_path, validators=[speleodb.utils.validators.AttachmentValidator()])),
                ('station', models.ForeignKey(help_text='The station or location this log entry is associated with.', on_delete=django.db.models.deletion.CASCADE, related_name='log_entries', to='gis.station')),
            ],
            options={
                'verbose_name_plural': 'Log Entries',
                'ordering': ['-creation_date'],
            },
        ),
        migrations.CreateModel(
            name='StationResource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('resource_type', models.CharField(choices=[('photo', 'Photo'), ('video', 'Video'), ('sketch', 'Sketch'), ('note', 'Note'), ('document', 'Document')], max_length=20)),
                ('title', models.CharField(help_text='Title or name of the resource', max_length=200)),
                ('description', models.TextField(blank=True, default='', help_text='Optional description of the resource')),
                ('file', models.FileField(blank=True, max_length=255, null=True, storage=speleodb.utils.storages.AttachmentStorage(), upload_to=speleodb.gis.models.station_resource.get_station_resource_path, validators=[speleodb.utils.validators.AttachmentValidator()])),
                ('miniature', models.ImageField(blank=True, help_text='Thumbnail/preview image for the resource', max_length=255, null=True, storage=speleodb.utils.storages.AttachmentStorage(), upload_to=speleodb.gis.models.station_resource.get_station_resource_path)),
                ('text_content', models.TextField(blank=True, default='', help_text='Text content for notes or sketch descriptions')),
                ('created_by', models.EmailField(help_text='User who created or submitted the entry.', max_length=254)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='gis.station')),
            ],
            options={
                'verbose_name': 'Station Resource',
                'verbose_name_plural': 'Station Resources',
                'ordering': ['station', '-modified_date'],
            },
        ),
        migrations.CreateModel(
            name='ExperimentRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data', models.JSONField(blank=True, default=dict, help_text='Data record for an experiment. Structure: {field_slug: value}. ')),
                ('created_by', models.EmailField(help_text='User who created or submitted the entry.', max_length=254)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rel_records', to='gis.experiment')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rel_records', to='gis.station')),
            ],
            options={
                'indexes': [models.Index(fields=['experiment', 'station'], name='gis_experim_experim_3267a9_idx')],
            },
        ),
        # Renaming `GeoJSON` to `ProjectGeoJSON` to avoid confusion
        migrations.RenameModel(
            old_name='GeoJSON',
            new_name='ProjectGeoJSON',
        ),
    ]
