# Generated by Django 5.2.8 on 2025-11-17 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gis', '0003_models_recreate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectgeojson',
            options={'verbose_name': 'Project GeoJSON', 'verbose_name_plural': 'Project GeoJSONs'},
        ),
    ]
