# Generated by Django 5.2.8 on 2025-11-17 17:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gis', '0004_alter_projectgeojson_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExperimentUserPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(choices=[(1, 'READ_ONLY'), (2, 'READ_AND_WRITE'), (3, 'ADMIN')], default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('deactivated_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rel_user_permissions', to='gis.experiment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rel_experiment_permissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Experiment - User Permission',
                'verbose_name_plural': 'Experiment - User Permissions',
                'indexes': [models.Index(fields=['user', 'is_active'], name='gis_experim_user_id_724cd1_idx'), models.Index(fields=['experiment', 'is_active'], name='gis_experim_experim_1bc171_idx'), models.Index(fields=['user', 'experiment', 'is_active'], name='gis_experim_user_id_c35a9a_idx')],
                'unique_together': {('user', 'experiment')},
            },
        ),
    ]
