# Generated by Django 5.2.8 on 2025-11-18 19:31

import django.db.models.deletion
import speleodb.gis.models.utils
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gis', '0005_experimentuserpermission'),
        ('surveys', '0018_project_permissions_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GISView',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Descriptive name for this GIS view', max_length=255)),
                ('description', models.TextField(blank=True, default='', help_text='Optional description of what this view contains')),
                ('gis_token', models.CharField(db_index=True, default=speleodb.gis.models.utils.generate_random_token, help_text='Unique token for API access to this view', max_length=40, unique=True, verbose_name='GIS View Token')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(help_text='User who owns and can manage this view', on_delete=django.db.models.deletion.CASCADE, related_name='owned_gis_views', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'GIS View',
                'verbose_name_plural': 'GIS Views',
                'ordering': ['-modified_date'],
            },
        ),
        migrations.CreateModel(
            name='GISViewProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commit_sha', models.CharField(blank=True, help_text='Specific commit SHA (40 hex chars). Leave empty if using latest.', max_length=40, null=True)),
                ('use_latest', models.BooleanField(default=False, help_text='If True, always use the latest commit. Takes precedence over commit_sha.')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('gis_view', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rel_view_projects', to='gis.gisview')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rel_gis_view_projects', to='surveys.project')),
            ],
            options={
                'verbose_name': 'GIS View Project',
                'verbose_name_plural': 'GIS View Projects',
                'ordering': ['creation_date'],
            },
        ),
        migrations.AddField(
            model_name='gisview',
            name='projects',
            field=models.ManyToManyField(help_text='Projects included in this view', related_name='rel_gis_views', through='gis.GISViewProject', to='surveys.project'),
        ),
        migrations.AddIndex(
            model_name='gisviewproject',
            index=models.Index(fields=['gis_view', 'project'], name='gis_gisview_gis_vie_02798c_idx'),
        ),
        migrations.AddConstraint(
            model_name='gisviewproject',
            constraint=models.CheckConstraint(condition=models.Q(('use_latest', True), models.Q(('commit_sha__gt', ''), ('commit_sha__isnull', False)), _connector='OR'), name='gisview_must_specify_commit_or_latest'),
        ),
        migrations.AlterUniqueTogether(
            name='gisviewproject',
            unique_together={('gis_view', 'project')},
        ),
        migrations.AddIndex(
            model_name='gisview',
            index=models.Index(fields=['owner'], name='gis_gisview_owner_i_ecdc7e_idx'),
        ),
        migrations.AddIndex(
            model_name='gisview',
            index=models.Index(fields=['gis_token'], name='gis_gisview_gis_tok_7a736b_idx'),
        ),
    ]
