# Generated by Django 5.2.8 on 2025-11-18 20:58

import django.core.validators
import django.db.models.deletion
import speleodb.gis.models.project_geojson
import speleodb.utils.storages
import speleodb.utils.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gis', '0006_gisview_gisviewproject_gisview_projects_and_more'),
        ('surveys', '0018_project_permissions_indexes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProjectGeoJSON',
        ),
        migrations.CreateModel(
            name='ProjectGeoJSON',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(storage=speleodb.utils.storages.GeoJSONStorage(), upload_to=speleodb.gis.models.project_geojson.get_geojson_upload_path, validators=[speleodb.utils.validators.GeoJsonValidator()])),
                ('commit_author_name', models.CharField(max_length=255, verbose_name='Name of User')),
                ('commit_author_email', models.EmailField(max_length=254, verbose_name='email address')),
                ('commit_message', models.CharField(max_length=1024, verbose_name='commit message')),
                ('commit_sha', models.CharField(max_length=40, unique=True, validators=[django.core.validators.RegexValidator(message='Enter a valid sha1 value', regex='^[0-9a-f]{40}$')])),
                ('commit_date', models.DateTimeField()),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rel_geojsons', to='surveys.project')),
            ],
            options={
                'verbose_name': 'Project GeoJSON',
                'verbose_name_plural': 'Project GeoJSONs',
            },
        ),
    ]
