# Generated by Django 5.2.8 on 2025-11-19 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gis', '0007_projectgeojson'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gisviewproject',
            name='commit_sha',
            field=models.CharField(blank=True, default='', help_text='Specific commit SHA (40 hex chars). Leave empty if using latest.', max_length=40),
        ),
    ]
