# Generated by Django 5.2.8 on 2025-11-19 06:12

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gis', '0008_gis_view_commit_sha_optional'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StationTag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="Tag name (e.g., 'Active', 'High Priority', 'Completed')", max_length=50)),
                ('color', models.CharField(help_text="Hex color code (e.g., '#FF5733')", max_length=7, validators=[django.core.validators.RegexValidator(message="Color must be a valid hex code (e.g., '#FF5733')", regex='^#[0-9A-Fa-f]{6}$')])),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(help_text='User who created the tag', on_delete=django.db.models.deletion.CASCADE, related_name='station_tags', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Station Tag',
                'verbose_name_plural': 'Station Tags',
                'ordering': ['user', 'name'],
                'unique_together': {('user', 'name')},
            },
        ),
        migrations.AddField(
            model_name='station',
            name='tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stations', to='gis.stationtag'),
        ),
    ]
