# Generated by Django 5.2.8 on 2025-11-20 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gis', '0009_stationtag_station_tag'),
        ('surveys', '0018_project_permissions_indexes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectgeojson',
            options={'ordering': ['-commit_date'], 'verbose_name': 'Project GeoJSON', 'verbose_name_plural': 'Project GeoJSONs'},
        ),
        migrations.AddIndex(
            model_name='projectgeojson',
            index=models.Index(fields=['project'], name='gis_project_project_f53e34_idx'),
        ),
        migrations.AddIndex(
            model_name='projectgeojson',
            index=models.Index(fields=['commit_date'], name='gis_project_commit__cbeaa2_idx'),
        ),
    ]
