# Generated by Django 5.2.8 on 2025-11-22 00:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gis', '0011_alter_experiment_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SensorFleet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="Sensor Fleet name (e.g., 'Flow Meters - Yucatan Peninsula')", max_length=50)),
                ('description', models.TextField(blank=True, default='', help_text='Optional description of the station')),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.EmailField(help_text='User who created the sensor fleet.', max_length=254)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Sensor Fleet',
                'verbose_name_plural': 'Sensor Fleets',
                'ordering': ['-modified_date'],
            },
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="Sensor name (e.g., 'Flow Meters #023')", max_length=50)),
                ('notes', models.TextField(blank=True, default='', help_text='Optional notes for the sensor')),
                ('is_functional', models.BooleanField(default=True)),
                ('created_by', models.EmailField(help_text='User who created the sensor fleet.', max_length=254)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('fleet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensors', to='gis.sensorfleet')),
            ],
            options={
                'ordering': ['-modified_date'],
            },
        ),
        migrations.CreateModel(
            name='SensorFleetUserPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(choices=[(1, 'READ_ONLY'), (2, 'READ_AND_WRITE'), (3, 'ADMIN')], default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('deactivated_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
                ('sensor_fleet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rel_user_permissions', to='gis.sensorfleet')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rel_sensorfleet_permissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sensor Fleet - User Permission',
                'verbose_name_plural': 'Sensor Fleet - User Permissions',
                'indexes': [models.Index(fields=['user', 'is_active'], name='gis_sensorf_user_id_0e5f16_idx'), models.Index(fields=['sensor_fleet', 'is_active'], name='gis_sensorf_sensor__08c0cf_idx'), models.Index(fields=['user', 'sensor_fleet', 'is_active'], name='gis_sensorf_user_id_89e54e_idx')],
                'unique_together': {('user', 'sensor_fleet')},
            },
        ),
    ]
