# Generated by Django 5.2.8 on 2025-11-25 06:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gis', '0012_sensorfleet_sensor_sensorfleetuserpermission'),
    ]

    operations = [
        migrations.CreateModel(
            name='SensorInstall',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('install_date', models.DateField()),
                ('install_user', models.EmailField(help_text='User who installed the sensor.', max_length=254)),
                ('uninstall_date', models.DateField(blank=True, default=None, null=True)),
                ('uninstall_user', models.EmailField(blank=True, default=None, help_text='User who retrieved the sensor.', max_length=254, null=True)),
                ('state', models.CharField(choices=[('installed', 'Installed'), ('retrieved', 'Retrieved'), ('lost', 'Lost'), ('abandoned', 'Abandoned')], default='installed', max_length=20)),
                ('expiracy_memory_date', models.DateField(blank=True, null=True)),
                ('expiracy_battery_date', models.DateField(blank=True, null=True)),
                ('created_by', models.EmailField(help_text='User who created the sensor fleet.', max_length=254)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installs', to='gis.sensor')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensor_installs', to='gis.station')),
            ],
            options={
                'verbose_name': 'Sensor Install',
                'verbose_name_plural': 'Sensor Installs',
                'ordering': ['-modified_date'],
                'indexes': [models.Index(fields=['state'], name='gis_sensori_state_194e83_idx'), models.Index(fields=['sensor', 'state'], name='gis_sensori_sensor__6f8f5d_idx'), models.Index(fields=['station', 'state'], name='gis_sensori_station_8c45ca_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(models.Q(('state', 'installed'), _negated=True), ('uninstall_date__isnull', False), ('uninstall_user__isnull', False)), models.Q(('state', 'installed'), ('uninstall_date__isnull', True), ('uninstall_user__isnull', True)), _connector='OR'), name='uninstall_fields_match_is_installed'), models.CheckConstraint(condition=models.Q(('uninstall_date__isnull', True), ('install_date__lte', models.F('uninstall_date')), _connector='OR'), name='install_before_or_equal_retrieval'), models.UniqueConstraint(condition=models.Q(('state', 'installed')), fields=('sensor',), name='unique_installed_per_sensor'), models.CheckConstraint(condition=models.Q(('expiracy_memory_date__isnull', True), ('install_date__lte', models.F('expiracy_memory_date')), _connector='OR'), name='install_before_or_equal_memory_expiracy'), models.CheckConstraint(condition=models.Q(('expiracy_battery_date__isnull', True), ('install_date__lte', models.F('expiracy_battery_date')), _connector='OR'), name='install_before_or_equal_battery_expiracy')],
            },
        ),
    ]
