# Generated by Django 5.2.8 on 2025-11-26 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gis', '0013_sensorinstall'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='sensorinstall',
            name='uninstall_fields_match_is_installed',
        ),
        migrations.RemoveConstraint(
            model_name='sensorinstall',
            name='unique_installed_per_sensor',
        ),
        migrations.RemoveIndex(
            model_name='sensorinstall',
            name='gis_sensori_state_194e83_idx',
        ),
        migrations.RemoveIndex(
            model_name='sensorinstall',
            name='gis_sensori_sensor__6f8f5d_idx',
        ),
        migrations.RemoveIndex(
            model_name='sensorinstall',
            name='gis_sensori_station_8c45ca_idx',
        ),
        migrations.RenameField(
            model_name='sensorinstall',
            old_name='state',
            new_name='status',
        ),
        migrations.RemoveField(
            model_name='sensor',
            name='is_functional',
        ),
        migrations.AddField(
            model_name='sensor',
            name='status',
            field=models.CharField(choices=[('functional', 'Functional'), ('broken', 'Broken'), ('lost', 'Lost'), ('abandoned', 'Abandoned')], default='functional', max_length=20),
        ),
        migrations.AddIndex(
            model_name='sensorinstall',
            index=models.Index(fields=['status'], name='gis_sensori_status_72957e_idx'),
        ),
        migrations.AddIndex(
            model_name='sensorinstall',
            index=models.Index(fields=['sensor', 'status'], name='gis_sensori_sensor__91b1a4_idx'),
        ),
        migrations.AddIndex(
            model_name='sensorinstall',
            index=models.Index(fields=['station', 'status'], name='gis_sensori_station_118421_idx'),
        ),
        migrations.AddConstraint(
            model_name='sensorinstall',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(models.Q(('status', 'installed'), _negated=True), ('uninstall_date__isnull', False), ('uninstall_user__isnull', False)), models.Q(('status', 'installed'), ('uninstall_date__isnull', True), ('uninstall_user__isnull', True)), _connector='OR'), name='uninstall_fields_match_is_installed'),
        ),
        migrations.AddConstraint(
            model_name='sensorinstall',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'installed')), fields=('sensor',), name='unique_installed_per_sensor'),
        ),
    ]
