# Generated by Django 5.2.8 on 2025-11-27 07:20

import django.db.models.deletion
import uuid
from django.db import migrations, models, connection


def inject_polymorphic_ctype(apps, schema_editor):
    Station = apps.get_model('gis', 'Station')
    SubSurfaceStation = apps.get_model('gis', 'SubSurfaceStation')
    ContentType = apps.get_model('contenttypes', 'ContentType')
    
    new_ct = ContentType.objects.get_for_model(SubSurfaceStation)
    Station.objects.filter(polymorphic_ctype__isnull=True).update(polymorphic_ctype=new_ct)


def migrate_stations_to_subsurface(apps, schema_editor):
    """
    Forward migration: Convert all existing Stations to SubSurfaceStations.
    
    Uses raw SQL to:
    1. Insert rows into gis_subsurfacestation linking to existing stations
    2. Set polymorphic_ctype for all migrated stations
    """

    with schema_editor.connection.cursor() as cursor:
        # Insert into child table directly - this links existing stations
        # to SubSurfaceStation without creating new Station rows
        cursor.execute('''
            INSERT INTO gis_subsurfacestation (station_ptr_id, project_id)
            SELECT id, _project_id FROM gis_station WHERE _project_id IS NOT NULL
        ''')


def reverse_migrate_to_base_stations(apps, schema_editor):
    """
    Reverse migration: Convert SubSurfaceStations back to base Stations.
    
    Uses raw SQL to:
    1. Copy project_id from SubSurfaceStation back to Station
    2. Clear polymorphic_ctype
    3. Delete SubSurfaceStation and SurfaceStation rows
    """    
    with schema_editor.connection.cursor() as cursor:
        # Copy project data back from SubSurfaceStation to Station
        # Uses PostgreSQL UPDATE...FROM syntax
        cursor.execute('''
            UPDATE gis_station 
            SET _project_id = ss.project_id
            FROM gis_subsurfacestation ss
            WHERE gis_station.id = ss.station_ptr_id
        ''')
        
        # Delete all child table rows (the Station rows remain intact)
        cursor.execute('DELETE FROM gis_subsurfacestation')



class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('gis', '0014_remove_sensorinstall_uninstall_fields_match_is_installed_and_more'),
        ('surveys', '0019_alter_format__format'),
    ]

   
    operations = [
        # ================================================================
        # STEP 1: Add polymorphic_ctype to Station (nullable for now)
        # ================================================================
        migrations.AddField(
            model_name='station',
            name='polymorphic_ctype',
            field=models.ForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='polymorphic_%(app_label)s.%(class)s_set+',
                to='contenttypes.contenttype',
            ),
        ),

        # ================================================================
        # STEP 2: Remove unique_together constraint and update ordering
        # Must happen BEFORE we remove the project field
        # ================================================================
        migrations.AlterUniqueTogether(
            name='station',
            unique_together=set(),
        ),
        migrations.AlterModelOptions(
            name='station',
            options={'ordering': ['-modified_date']},
        ),

        # ================================================================
        # STEP 3: Remove project from Station's STATE only (keep DB column)
        # This MUST happen before creating SubSurfaceStation to avoid
        # field name clash between parent and child
        # ================================================================
        migrations.AlterField(
            model_name='station',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rel_stations', to='surveys.project', null=True, blank=True),
        ),

        migrations.RenameField(
            model_name='station',
            old_name='project',
            new_name='_project'
        ),

        # ================================================================
        # STEP 4: Create SubSurfaceStation and SurfaceStation
        # Now safe to create since Station no longer has 'project' in state
        # ================================================================
        migrations.CreateModel(
            name='SubSurfaceStation',
            fields=[
                ('station_ptr', models.OneToOneField(
                    auto_created=True,
                    on_delete=django.db.models.deletion.CASCADE,
                    parent_link=True,
                    primary_key=True,
                    serialize=False,
                    to='gis.station',
                )),
                ('project', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='rel_stations',
                    to='surveys.project',
                )),
            ],
            options={'verbose_name': 'Station - Subsurface', 'verbose_name_plural': 'Stations - Subsurface'},
            bases=('gis.station',),
        ),
        migrations.RunPython(inject_polymorphic_ctype, migrations.RunPython.noop),

        # ================================================================
        # STEP 5: Data migration - convert existing Stations to SubSurfaceStations
        # Uses raw SQL to INSERT directly into child table
        # ================================================================
        migrations.RunPython(
            code=migrate_stations_to_subsurface,
            reverse_code=reverse_migrate_to_base_stations,
        ),

        # ================================================================
        # STEP 6: Remove project column from database using RunPython
        # State was already updated in step 3
        # ================================================================
        migrations.RemoveField(
            model_name='station',
            name='_project',
        ),
    ] 