# Generated by Django 5.2.8 on 2025-11-27 07:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


def migrate_stations_to_subsurface(apps, schema_editor):
    """
    Forward migration: Convert all existing Stations to SubsurfaceStations.
    
    For each existing Station with a project:
    1. Create a SubsurfaceStation row pointing to the Station
    2. Set the polymorphic_ctype to SubsurfaceStation's ContentType
    
    Note: At this point, Django state doesn't have project on Station,
    but the database still has the project_id column. We use raw SQL
    to read the project_id values.
    """
    SubsurfaceStation = apps.get_model('gis', 'SubsurfaceStation')
    ContentType = apps.get_model('contenttypes', 'ContentType')
    
    # Get or create the ContentType for SubsurfaceStation
    subsurface_ct, _ = ContentType.objects.get_or_create(
        app_label='gis',
        model='subsurfacestation',
    )
    
    # Use raw SQL to get station data since Django state doesn't have project field
    with schema_editor.connection.cursor() as cursor:
        cursor.execute(
            'SELECT id, project_id FROM gis_station WHERE project_id IS NOT NULL'
        )
        rows = cursor.fetchall()
    
    # For each existing station with a project, create a SubsurfaceStation entry
    for station_id, project_id in rows:
        # Create SubsurfaceStation row
        SubsurfaceStation.objects.create(
            station_ptr_id=station_id,
            project_id=project_id,
        )
    
    # Update polymorphic_ctype for all migrated stations
    with schema_editor.connection.cursor() as cursor:
        cursor.execute(
            '''UPDATE gis_station 
               SET polymorphic_ctype_id = %s 
               WHERE id IN (SELECT station_ptr_id FROM gis_subsurfacestation)''',
            [subsurface_ct.pk]
        )


def reverse_migrate_to_base_stations(apps, schema_editor):
    """
    Reverse migration: Convert SubsurfaceStations back to base Stations.
    
    1. Copy project_id from SubsurfaceStation back to Station (via raw SQL)
    2. Delete SubsurfaceStation rows
    3. Clear polymorphic_ctype
    
    Note: At this point the project_id column has been restored by the
    RunSQL reverse operation.
    """
    SubsurfaceStation = apps.get_model('gis', 'SubsurfaceStation')
    SurfaceStation = apps.get_model('gis', 'SurfaceStation')
    
    # Copy project data back from SubsurfaceStation to Station using raw SQL
    with schema_editor.connection.cursor() as cursor:
        cursor.execute('''
            UPDATE gis_station 
            SET project_id = (
                SELECT project_id 
                FROM gis_subsurfacestation 
                WHERE gis_subsurfacestation.station_ptr_id = gis_station.id
            ),
            polymorphic_ctype_id = NULL
            WHERE id IN (SELECT station_ptr_id FROM gis_subsurfacestation)
        ''')
    
    # Delete all child table rows (the Station rows remain)
    SubsurfaceStation.objects.all().delete()
    SurfaceStation.objects.all().delete()


class Migration(migrations.Migration):
    # Non-atomic migration required because:
    # 1. Forward: We do data migration (INSERT/UPDATE) then ALTER TABLE
    # 2. Reverse: We do data migration (UPDATE/DELETE) then ALTER TABLE (unique_together)
    # PostgreSQL doesn't allow ALTER TABLE with pending trigger events in same transaction
    atomic = False

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('gis', '0014_remove_sensorinstall_uninstall_fields_match_is_installed_and_more'),
        ('surveys', '0019_alter_format__format'),
    ]

    operations = [
        # ================================================================
        # STEP 1: Create MonitoringNetwork model
        # ================================================================
        migrations.CreateModel(
            name='MonitoringNetwork',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="Monitoring network identifier (e.g., 'A1', 'Network-001')", max_length=100)),
                ('description', models.TextField(blank=True, default='', help_text='Optional description of the network')),
                ('created_by', models.EmailField(help_text='User who created or submitted the entry.', max_length=254)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
            ]
        ),

        # ================================================================
        # STEP 2: Add polymorphic_ctype to Station (nullable for now)
        # ================================================================
        migrations.AddField(
            model_name='station',
            name='polymorphic_ctype',
            field=models.ForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='polymorphic_%(app_label)s.%(class)s_set+',
                to='contenttypes.contenttype',
            ),
        ),

        # ================================================================
        # STEP 3: Remove unique_together constraint and update ordering
        # Must happen BEFORE we remove the project field
        # ================================================================
        migrations.AlterUniqueTogether(
            name='station',
            unique_together=set(),
        ),
        migrations.AlterModelOptions(
            name='station',
            options={
                'ordering': ['-modified_date'],
                'verbose_name': 'Station',
                'verbose_name_plural': 'Stations',
            },
        ),

        # ================================================================
        # STEP 4: Remove project from Station's STATE only (keep DB column)
        # This MUST happen before creating SubsurfaceStation to avoid
        # field name clash between parent and child
        # ================================================================
        migrations.SeparateDatabaseAndState(
            database_operations=[
                # Keep project_id column in database - don't do anything
            ],
            state_operations=[
                # Remove project from Station's state
                migrations.RemoveField(
                    model_name='station',
                    name='project',
                ),
            ],
        ),

        # ================================================================
        # STEP 5: Create SubsurfaceStation and SurfaceStation
        # Now safe to create since Station no longer has 'project' in state
        # ================================================================
        migrations.CreateModel(
            name='SubsurfaceStation',
            fields=[
                ('station_ptr', models.OneToOneField(
                    auto_created=True,
                    on_delete=django.db.models.deletion.CASCADE,
                    parent_link=True,
                    primary_key=True,
                    serialize=False,
                    to='gis.station',
                )),
                ('project', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='rel_stations',
                    to='surveys.project',
                )),
            ],
            options={
                'verbose_name': 'Subsurface Station',
                'verbose_name_plural': 'Subsurface Stations',
            },
            bases=('gis.station',),
        ),
        migrations.CreateModel(
            name='SurfaceStation',
            fields=[
                ('station_ptr', models.OneToOneField(
                    auto_created=True,
                    on_delete=django.db.models.deletion.CASCADE,
                    parent_link=True,
                    primary_key=True,
                    serialize=False,
                    to='gis.station',
                )),
                ('network', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='rel_stations',
                    to='gis.monitoringnetwork',
                )),
            ],
            options={
                'verbose_name': 'Surface Station',
                'verbose_name_plural': 'Surface Stations',
            },
            bases=('gis.station',),
        ),

        # ================================================================
        # STEP 6: Data migration - convert existing Stations to SubsurfaceStations
        # Uses raw SQL since Django state doesn't have project on Station
        # ================================================================
        migrations.RunPython(
            code=migrate_stations_to_subsurface,
            reverse_code=reverse_migrate_to_base_stations,
        ),

        # ================================================================
        # STEP 7: Remove project column from database using raw SQL
        # Using RunSQL instead of RemoveField to avoid state conflicts
        # State was already updated in step 4
        # ================================================================
        migrations.RunSQL(
            sql='ALTER TABLE gis_station DROP COLUMN project_id;',
            reverse_sql='ALTER TABLE gis_station ADD COLUMN project_id uuid REFERENCES surveys_project(id) ON DELETE CASCADE;',
        ),
    ]
