# Generated by Django 5.2.8 on 2025-11-27 08:36

import django.db.models.deletion
import uuid
from django.db import migrations, models
from django.conf import settings


class Migration(migrations.Migration):

    dependencies = [
        ('gis', '0015_station_polymorphism'),
    ]

    operations = [
        # ================================================================
        # STEP 1: Create MonitoringNetwork model
        # ================================================================
        migrations.CreateModel(
            name='MonitoringNetwork',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="Monitoring network identifier (e.g., 'A1', 'Network-001')", max_length=100)),
                ('description', models.TextField(blank=True, default='', help_text='Optional description of the network')),
                ('created_by', models.EmailField(help_text='User who created or submitted the entry.', max_length=254)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
            ]
        ),

        # ================================================================
        # STEP 2: Create MonitoringNetworkUserPermission model
        # ================================================================
        migrations.CreateModel(
            name='MonitoringNetworkUserPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(choices=[(1, 'READ_ONLY'), (2, 'READ_AND_WRITE'), (3, 'ADMIN')], default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('deactivated_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
                ('network', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='gis.monitoringnetwork')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='network_permissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Monitoring Network - User Permission',
                'verbose_name_plural': 'Monitoring Network - User Permissions',
                'indexes': [models.Index(fields=['user', 'is_active'], name='gis_monitor_user_id_1f661f_idx'), models.Index(fields=['network', 'is_active'], name='gis_monitor_network_ab1146_idx'), models.Index(fields=['user', 'network', 'is_active'], name='gis_monitor_user_id_fa9e55_idx')],
                'unique_together': {('user', 'network')},
            },
        ),

        # ================================================================
        # STEP 3: Create SurfaceStation model
        # ================================================================
        migrations.CreateModel(
            name='SurfaceStation',
            fields=[
                ('station_ptr', models.OneToOneField(
                    auto_created=True,
                    on_delete=django.db.models.deletion.CASCADE,
                    parent_link=True,
                    primary_key=True,
                    serialize=False,
                    to='gis.station',
                )),
                ('network', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='rel_stations',
                    to='gis.monitoringnetwork',
                )),
            ],
            options={
                'verbose_name': 'Station - Surface',
                'verbose_name_plural': 'Stations - Surface',
            },
            bases=('gis.station',),
        ),
    ]
