# Generated by Django 5.2.8 on 2025-11-27 08:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gis', '0015_station_polymorphism'),
    ]

    operations = [
        # ================================================================
        # STEP 1: Create MonitoringNetwork model
        # ================================================================
        migrations.CreateModel(
            name='MonitoringNetwork',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="Monitoring network identifier (e.g., 'A1', 'Network-001')", max_length=100)),
                ('description', models.TextField(blank=True, default='', help_text='Optional description of the network')),
                ('created_by', models.EmailField(help_text='User who created or submitted the entry.', max_length=254)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
            ]
        ),

        # ================================================================
        # STEP 2: Create SurfaceStation model
        # ================================================================
        migrations.CreateModel(
            name='SurfaceStation',
            fields=[
                ('station_ptr', models.OneToOneField(
                    auto_created=True,
                    on_delete=django.db.models.deletion.CASCADE,
                    parent_link=True,
                    primary_key=True,
                    serialize=False,
                    to='gis.station',
                )),
                ('network', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='rel_stations',
                    to='gis.monitoringnetwork',
                )),
            ],
            options={
                'verbose_name': 'Station - Surface',
                'verbose_name_plural': 'Stations - Surface',
            },
            bases=('gis.station',),
        ),
    ]
