# Generated by Django 5.2.8 on 2025-11-30 16:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gis', '0017_surface_networks'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # =================================================================== #
        # Rename PointOfInterest model to Landmark
        # =================================================================== #
        migrations.RemoveIndex(
            model_name='pointofinterest',
            name='surveys_poi_creatio_9acde1_idx',
        ),
        migrations.RemoveIndex(
            model_name='pointofinterest',
            name='surveys_poi_latitud_22d2b1_idx',
        ),
        migrations.RemoveIndex(
            model_name='pointofinterest',
            name='surveys_poi_name_59f0fd_idx',
        ),
        migrations.RemoveIndex(
            model_name='pointofinterest',
            name='surveys_poi_user_id_4185ea_idx',
        ),
        migrations.RenameModel(
            old_name='PointOfInterest',
            new_name='Landmark',
        ),
        migrations.AlterModelOptions(
            name='landmark',
            options={'ordering': ['name'], 'verbose_name': 'Landmark', 'verbose_name_plural': 'Landmarks'},
        ),
        migrations.AlterField(
            model_name='landmark',
            name='name',
            field=models.CharField(help_text='Landmark name', max_length=100),
        ),
        migrations.AddIndex(
            model_name='landmark',
            index=models.Index(fields=['latitude', 'longitude'], name='gis_landmar_latitud_68b766_idx'),
        ),
        migrations.AddIndex(
            model_name='landmark',
            index=models.Index(fields=['name'], name='gis_landmar_name_692326_idx'),
        ),
        migrations.AddIndex(
            model_name='landmark',
            index=models.Index(fields=['creation_date'], name='gis_landmar_creatio_494558_idx'),
        ),
        migrations.AddIndex(
            model_name='landmark',
            index=models.Index(fields=['user'], name='gis_landmar_user_id_9f3bfc_idx'),
        ),
        # =================================================================== #
        # Rename LogEntry model to StationLogEntry
        # =================================================================== #
        migrations.RenameModel(
            old_name='LogEntry',
            new_name='StationLogEntry',
        ),
    ]
