# Generated by Django 5.2.8 on 2025-11-30 17:30

import speleodb.gis.models.utils
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('gis', '0018_model_renaming_and_missing_indexes'),
        ('surveys', '0019_alter_format__format'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='gisview',
            name='gis_gisview_gis_tok_7a736b_idx',
        ),
        migrations.RemoveIndex(
            model_name='gisviewproject',
            name='gis_gisview_gis_vie_02798c_idx',
        ),
        migrations.RemoveIndex(
            model_name='sensorinstall',
            name='gis_sensori_status_72957e_idx',
        ),
        migrations.RemoveIndex(
            model_name='sensorinstall',
            name='gis_sensori_sensor__91b1a4_idx',
        ),
        migrations.RemoveIndex(
            model_name='sensorinstall',
            name='gis_sensori_station_118421_idx',
        ),
        migrations.AlterField(
            model_name='gisview',
            name='gis_token',
            field=models.CharField(default=speleodb.gis.models.utils.generate_random_token, help_text='Unique token for API access to this view', max_length=40, unique=True, verbose_name='GIS View Token'),
        ),
        migrations.AddIndex(
            model_name='experiment',
            index=models.Index(fields=['code'], name='gis_experim_code_d9a6c8_idx'),
        ),
        migrations.AddIndex(
            model_name='experimentrecord',
            index=models.Index(fields=['experiment'], name='gis_experim_experim_8e1b57_idx'),
        ),
        migrations.AddIndex(
            model_name='gisviewproject',
            index=models.Index(fields=['gis_view'], name='gis_gisview_gis_vie_bf3637_idx'),
        ),
        migrations.AddIndex(
            model_name='projectgeojson',
            index=models.Index(fields=['commit_sha'], name='gis_project_commit__5625bd_idx'),
        ),
        migrations.AddIndex(
            model_name='projectgeojson',
            index=models.Index(fields=['project', 'commit_date'], name='gis_project_project_204292_idx'),
        ),
        migrations.AddIndex(
            model_name='sensor',
            index=models.Index(fields=['fleet'], name='gis_sensor_fleet_i_0a1a9f_idx'),
        ),
        migrations.AddIndex(
            model_name='sensor',
            index=models.Index(fields=['status'], name='gis_sensor_status_b5cd2b_idx'),
        ),
        migrations.AddIndex(
            model_name='sensor',
            index=models.Index(fields=['fleet', 'status'], name='gis_sensor_fleet_i_4912b1_idx'),
        ),
        migrations.AddIndex(
            model_name='sensorfleet',
            index=models.Index(fields=['is_active'], name='gis_sensorf_is_acti_c4d435_idx'),
        ),
        migrations.AddIndex(
            model_name='sensorinstall',
            index=models.Index(fields=['sensor'], name='gis_sensori_sensor__adb1cf_idx'),
        ),
        migrations.AddIndex(
            model_name='sensorinstall',
            index=models.Index(fields=['station'], name='gis_sensori_station_fe5431_idx'),
        ),
        migrations.AddIndex(
            model_name='sensorinstall',
            index=models.Index(fields=['sensor', 'station'], name='gis_sensori_sensor__49b499_idx'),
        ),
        migrations.AddIndex(
            model_name='station',
            index=models.Index(fields=['tag'], name='gis_station_tag_id_1c9dbc_idx'),
        ),
        migrations.AddIndex(
            model_name='station',
            index=models.Index(fields=['latitude', 'longitude'], name='gis_station_latitud_76cc8f_idx'),
        ),
        migrations.AddIndex(
            model_name='stationlogentry',
            index=models.Index(fields=['station'], name='gis_station_station_14fa66_idx'),
        ),
        migrations.AddIndex(
            model_name='stationresource',
            index=models.Index(fields=['station'], name='gis_station_station_acbb39_idx'),
        ),
        migrations.AddIndex(
            model_name='stationtag',
            index=models.Index(fields=['user'], name='gis_station_user_id_b0ea4b_idx'),
        ),
        migrations.AddIndex(
            model_name='subsurfacestation',
            index=models.Index(fields=['project'], name='gis_subsurf_project_2ce9c3_idx'),
        ),
        migrations.AddIndex(
            model_name='surfacestation',
            index=models.Index(fields=['network'], name='gis_surface_network_bcf70f_idx'),
        ),
    ]
