# Generated by Django 5.2.9 on 2025-12-04 05:06

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gis', '0019_index_optimizations'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='landmark',
            name='description',
            field=models.TextField(blank=True, default='', help_text='Optional description of the landmark'),
        ),
        migrations.AlterField(
            model_name='landmark',
            name='latitude',
            field=models.DecimalField(decimal_places=7, help_text='Landmark latitude coordinate', max_digits=10, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)]),
        ),
        migrations.AlterField(
            model_name='landmark',
            name='longitude',
            field=models.DecimalField(decimal_places=7, help_text='Landmark longitude coordinate', max_digits=10, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)]),
        ),
        migrations.AlterField(
            model_name='landmark',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='landmarks', to=settings.AUTH_USER_MODEL),
        ),
    ]
