# Generated by Django 5.2.9 on 2025-12-04 05:06

import django.db.models.deletion
from django.db import migrations, models


def forward_commit_propagation(apps, schema_editor):
    ProjectCommit = apps.get_model('surveys', 'ProjectCommit')
    ProjectGeoJSON = apps.get_model('gis', 'ProjectGeoJSON')
    
    for project in ProjectGeoJSON.objects.all():
        project.commit = ProjectCommit.objects.get(id=project.commit_sha)
        project.save()


def backward_commit_propagation(apps, schema_editor):
    ProjectGeoJSON = apps.get_model('gis', 'ProjectGeoJSON')
    
    for project in ProjectGeoJSON.objects.all():
        project.commit_sha = project.commit.id
        project.commit_message = project.commit.message
        project.commit_author_name = project.commit.author_name
        project.commit_author_email = project.commit.author_email
        project.commit_date = project.commit.authored_date
        project.save()


class Migration(migrations.Migration):

    dependencies = [
        ('gis', '0020_landmark_cleanup'),
        ('surveys', '0023_index_optimizations'),
    ]

    operations = [
        # Add One-To-One Relationship: For now nullable
        # =====================================================================
        migrations.AddField(
            model_name='projectgeojson',
            name='commit',
            field=models.OneToOneField( 
                editable=False, 
                on_delete=django.db.models.deletion.CASCADE, 
                related_name='geojson', 
                to='surveys.projectcommit',
                null=True
            ),
            preserve_default=False,
        ),

        # Copy the information transformed in the old fields
        # =====================================================================
        migrations.RunPython(
            forward_commit_propagation, 
            migrations.RunPython.noop
        ),

        # Restore not NULL in the One-To-One relationship
        # =====================================================================
        migrations.AlterField(
            model_name='projectgeojson',
            name='commit',
            field=models.OneToOneField(
                editable=False, 
                on_delete=django.db.models.deletion.CASCADE, 
                related_name='geojson', 
                to='surveys.projectcommit'
            ),
        ),

        # Clean Model State
        # =====================================================================
        migrations.AlterModelOptions(
            name='projectgeojson',
            options={'ordering': ['-commit__authored_date'], 'verbose_name': 'Project GeoJSON', 'verbose_name_plural': 'Project GeoJSONs'},
        ),
        migrations.RemoveIndex(
            model_name='projectgeojson',
            name='gis_project_commit__cbeaa2_idx',
        ),
        migrations.RemoveIndex(
            model_name='projectgeojson',
            name='gis_project_commit__5625bd_idx',
        ),
        migrations.RemoveIndex(
            model_name='projectgeojson',
            name='gis_project_project_204292_idx',
        ),

        # Make fields nullable for reverse migration
        # =====================================================================
        migrations.AlterField(
            model_name='projectgeojson',
            name='commit_sha',
            field=models.CharField(
                unique=False,
                null=True
            ),
        ),
        migrations.AlterField(
            model_name='projectgeojson',
            name='commit_message',
            field=models.CharField(
                null=True
            ),
        ),
        migrations.AlterField(
            model_name='projectgeojson',
            name='commit_author_name',
            field=models.CharField(
                null=True
            ),
        ),
        migrations.AlterField(
            model_name='projectgeojson',
            name='commit_author_email',
            field=models.CharField(
                null=True
            ),
        ),
        migrations.AlterField(
            model_name='projectgeojson',
            name='commit_date',
            field=models.CharField(
                null=True
            ),
        ),
        
        migrations.RunPython(migrations.RunPython.noop, backward_commit_propagation),

        # Remove Fields
        # =====================================================================
        migrations.RemoveField(
            model_name='projectgeojson',
            name='commit_author_email',
        ),
        migrations.RemoveField(
            model_name='projectgeojson',
            name='commit_author_name',
        ),
        migrations.RemoveField(
            model_name='projectgeojson',
            name='commit_date',
        ),
        migrations.RemoveField(
            model_name='projectgeojson',
            name='commit_message',
        ),
        migrations.RemoveField(
            model_name='projectgeojson',
            name='commit_sha',
        ),

        # Add Model Indexes
        # =====================================================================
        migrations.AddIndex(
            model_name='projectgeojson',
            index=models.Index(fields=['commit'], name='gis_project_commit__dd1599_idx'),
        ),

        # Transfer the primary key to `commit`
        # =====================================================================
        migrations.RemoveField(
            model_name='projectgeojson',
            name='id',
        ),
        migrations.AlterField(
            model_name='projectgeojson',
            name='commit',
            field=models.OneToOneField(
                editable=False, 
                on_delete=django.db.models.deletion.CASCADE, 
                primary_key=True, 
                related_name='geojson', 
                serialize=False, 
                to='surveys.projectcommit'
            ),
        ),
    ]
