# Generated by Django 5.2.9 on 2025-12-06 19:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gis', '0021_projectgeojson_commit'),
        ('surveys', '0024_related_fields_rename'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='experimentrecord',
            name='experiment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='gis.experiment'),
        ),
        migrations.AlterField(
            model_name='experimentrecord',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='gis.station'),
        ),
        migrations.AlterField(
            model_name='experimentuserpermission',
            name='experiment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_permissions', to='gis.experiment'),
        ),
        migrations.AlterField(
            model_name='experimentuserpermission',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiment_permissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='gisview',
            name='projects',
            field=models.ManyToManyField(help_text='Projects included in this view', related_name='gis_views', through='gis.GISViewProject', to='surveys.project'),
        ),
        migrations.AlterField(
            model_name='gisviewproject',
            name='gis_view',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='view_projects', to='gis.gisview'),
        ),
        migrations.AlterField(
            model_name='gisviewproject',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='view_projects', to='surveys.project'),
        ),
        migrations.AlterField(
            model_name='projectgeojson',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='geojsons', to='surveys.project'),
        ),
        migrations.AlterField(
            model_name='sensorfleetuserpermission',
            name='sensor_fleet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_permissions', to='gis.sensorfleet'),
        ),
        migrations.AlterField(
            model_name='sensorfleetuserpermission',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensorfleet_permissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='subsurfacestation',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stations', to='surveys.project'),
        ),
        migrations.AlterField(
            model_name='surfacestation',
            name='network',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stations', to='gis.surfacemonitoringnetwork'),
        ),
    ]
