# Generated by Django 5.2.9 on 2025-12-06 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gis', '0022_related_fields_rename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stationresource',
            name='resource_type',
            field=models.CharField(choices=[('photo', 'Photo'), ('video', 'Video'), ('note', 'Note'), ('document', 'Document')], max_length=20),
        ),
        migrations.AlterField(
            model_name='stationresource',
            name='text_content',
            field=models.TextField(blank=True, default='', help_text='Text content for notes descriptions'),
        ),
    ]
