# Generated by Django 5.2.9 on 2025-12-06 22:52

from django.db import migrations
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gis', '0023_station_resource_sketch_removal'),
        ('surveys', '0024_related_fields_rename'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GISViewProject',
            new_name='GISProjectView',
        ),
        migrations.AlterModelOptions(
            name='gisprojectview',
            options={'ordering': ['creation_date'], 'verbose_name': 'GIS Project View', 'verbose_name_plural': 'GIS Project Views'},
        ),
        migrations.RenameIndex(
            model_name='gisprojectview',
            new_name='gis_gisproj_gis_vie_5120dc_idx',
            old_name='gis_gisview_gis_vie_bf3637_idx',
        ),
        migrations.AlterField(
            model_name='gisprojectview',
            name='gis_view',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_views', to='gis.gisview'),
        ),
        migrations.AlterField(
            model_name='gisprojectview',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_views', to='surveys.project'),
        ),
    ]
