# Generated by Django 6.0 on 2026-01-06 03:23

import django.core.validators
import django.db.models.deletion
import speleodb.gis.models.gps_track
import speleodb.surveys.fields
import speleodb.utils.storages
import speleodb.utils.validators
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gis', '0024_rename_gisviewproject_gisprojectview'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GPSTrack',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Track name', max_length=255)),
                ('file', models.FileField(storage=speleodb.utils.storages.GPSTrackStorage(), upload_to=speleodb.gis.models.gps_track.get_gps_track_upload_path, validators=[speleodb.utils.validators.GeoJsonValidator()])),
                ('sha256_hash', speleodb.surveys.fields.Sha256Field(max_length=64, unique=True, validators=[django.core.validators.RegexValidator(message='Enter a valid sha256 value', regex='^[a-fA-F0-9]{64}$')], verbose_name='SHA256 hash of the `geojson file`')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gps_tracks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'GPS Track',
                'verbose_name_plural': 'GPS Tracks',
                'ordering': ['-creation_date'],
                'indexes': [models.Index(fields=['user'], name='gis_gpstrac_user_id_7dba81_idx'), models.Index(fields=['sha256_hash'], name='gis_gpstrac_sha256__b30baf_idx')],
            },
        ),
    ]
