# Generated by Django 6.0 on 2026-01-07 03:17

import django.core.validators
import speleodb.surveys.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gis', '0025_gpstrack'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='gpstrack',
            name='sha256_hash',
            field=speleodb.surveys.fields.Sha256Field(max_length=64, validators=[django.core.validators.RegexValidator(message='Enter a valid sha256 value', regex='^[a-fA-F0-9]{64}$')], verbose_name='SHA256 hash of the `geojson file`'),
        ),
        migrations.AddConstraint(
            model_name='gpstrack',
            constraint=models.UniqueConstraint(fields=('sha256_hash', 'user'), name='unique_gps_track_per_user'),
        ),
        migrations.AddConstraint(
            model_name='landmark',
            constraint=models.UniqueConstraint(fields=('latitude', 'longitude', 'user'), name='unique_landmark_per_user'),
        ),
    ]
