# Generated by Django 6.0 on 2026-01-02 05:21

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gis', '0026_alter_gpstrack_sha256_hash_and_more'),
        ('surveys', '0024_related_fields_rename'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExplorationLead',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True, default='', help_text='Optional description of the lead')),
                ('latitude', models.DecimalField(decimal_places=7, help_text='Station latitude coordinate', max_digits=10, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)])),
                ('longitude', models.DecimalField(decimal_places=7, help_text='Station longitude coordinate', max_digits=10, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)])),
                ('created_by', models.EmailField(help_text='User who created or submitted the entry.', max_length=254)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exploration_leads', to='surveys.project')),
            ],
            options={
                'verbose_name': 'Exploration Lead',
                'verbose_name_plural': 'Exploration Leads',
                'ordering': ['-modified_date'],
                'indexes': [models.Index(fields=['latitude', 'longitude'], name='gis_explora_latitud_f344f6_idx'), models.Index(fields=['project'], name='gis_explora_project_8703d7_idx')],
            },
        ),
    ]
