# Generated by Django 6.0.1 on 2026-01-16 04:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gis', '0027_explorationlead'),
        ('surveys', '0026_unique_together_update'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Adjust Enum Field to Add "Needs Service"
        migrations.AlterField(
            model_name='sensor',
            name='status',
            field=models.CharField(choices=[('functional', 'Functional'), ('needs_service', 'Needs Service'), ('broken', 'Broken'), ('lost', 'Lost'), ('abandoned', 'Abandoned')], default='functional', max_length=20),
        ),
        # Removal of the previous "unique constraints"
        migrations.AlterUniqueTogether(
            name='experimentuserpermission',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='gisprojectview',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='sensorfleetuserpermission',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='stationtag',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='surfacemonitoringnetworkuserpermission',
            unique_together=set(),
        ),
        migrations.RemoveConstraint(
            model_name='sensorinstall',
            name='unique_installed_per_sensor',
        ),
        migrations.RemoveConstraint(
            model_name='gpstrack',
            name='unique_gps_track_per_user',
        ),
        migrations.RemoveConstraint(
            model_name='landmark',
            name='unique_landmark_per_user',
        ),
        # Adding them back in the new "django way"
        migrations.AddConstraint(
            model_name='experimentuserpermission',
            constraint=models.UniqueConstraint(fields=('user', 'experiment'), name='gis_experimentuserpermission_user_experiment_perm_unique'),
        ),
        migrations.AddConstraint(
            model_name='gisprojectview',
            constraint=models.UniqueConstraint(fields=('gis_view', 'project'), name='gis_gisprojectview_project_gis_view_unique'),
        ),
        migrations.AddConstraint(
            model_name='sensorfleetuserpermission',
            constraint=models.UniqueConstraint(fields=('user', 'sensor_fleet'), name='gis_sensorfleetuserpermission_user_sensor_fleet_perm_unique'),
        ),
        migrations.AddConstraint(
            model_name='stationtag',
            constraint=models.UniqueConstraint(fields=('user', 'name'), name='gis_stationtag_user_tag_unique'),
        ),
        migrations.AddConstraint(
            model_name='surfacemonitoringnetworkuserpermission',
            constraint=models.UniqueConstraint(fields=('user', 'network'), name='gis_surfacemonitoringnetworkuserpermission_user_network_perm_unique'),
        ),
        migrations.AddConstraint(
            model_name='sensorinstall',
            constraint=models.UniqueConstraint(
                condition=models.Q(('status', 'installed')), 
                fields=('sensor',), 
                name='gis_sensorinstall_installed_per_sensor_unique'
            ),
        ),
        migrations.AddConstraint(
            model_name='gpstrack',
            constraint=models.UniqueConstraint(fields=('sha256_hash', 'user'), name='gis_gpstrack_gps_track_per_user_unique'),
        ),
        migrations.AddConstraint(
            model_name='landmark',
            constraint=models.UniqueConstraint(fields=('latitude', 'longitude', 'user'), name='gis_landmark_landmark_per_user_unique'),
        ),
        # Renaming some constraints to prepare for cylinders
        migrations.RemoveConstraint(
            model_name='sensorinstall',
            name='install_before_or_equal_retrieval',
        ),
        migrations.RemoveConstraint(
            model_name='sensorinstall',
            name='uninstall_fields_match_is_installed',
        ),
        migrations.AddConstraint(
            model_name='sensorinstall',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(models.Q(('status', 'installed'), _negated=True), ('uninstall_date__isnull', False), ('uninstall_user__isnull', False)), models.Q(('status', 'installed'), ('uninstall_date__isnull', True), ('uninstall_user__isnull', True)), _connector='OR'), name='sensor_uninstall_fields_match_is_installed'),
        ),
        migrations.AddConstraint(
            model_name='sensorinstall',
            constraint=models.CheckConstraint(condition=models.Q(('uninstall_date__isnull', True), ('install_date__lte', models.F('uninstall_date')), _connector='OR'), name='sensor_install_before_or_equal_retrieval'),
        ),
    ]
