# Generated by Django 6.0.1 on 2026-01-18 14:31

import django.core.validators
import django.db.models.deletion
import django.db.models.expressions
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gis', '0028_cleanup_constraints_and_enums'),
        ('surveys', '0026_unique_together_update'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CylinderFleet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="Cylinder Fleet name (e.g., 'Wakulla Project Cylinders')", max_length=50)),
                ('description', models.TextField(blank=True, default='', help_text='Optional description of the cylinder fleet')),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.EmailField(help_text='User who created the cylinder fleet.', max_length=254)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cylinder Fleet',
                'verbose_name_plural': 'Cylinder Fleets',
                'ordering': ['-modified_date'],
                'indexes': [models.Index(fields=['is_active'], name='gis_cylinde_is_acti_123e03_idx')],
            },
        ),
        migrations.CreateModel(
            name='Cylinder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, help_text="Cylinder name (e.g., 'Cylinder #023')", max_length=50)),
                ('serial', models.CharField(blank=True, help_text='Cylinder Serial Number', max_length=15)),
                ('brand', models.CharField(blank=True, help_text='Cylinder Brand: Luxfer, Catalina, etc.', max_length=50)),
                ('owner', models.CharField(blank=True, help_text="Cylinder owner (e.g., 'John Doe')", max_length=255)),
                ('notes', models.TextField(blank=True, help_text='Optional notes for the cylinder')),
                ('type', models.CharField(blank=True, help_text="Cylinder type/model (e.g., 'AL80, AL40')", max_length=100)),
                ('o2_percentage', models.IntegerField(help_text="O2 percentage (e.g., '21%')", validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('he_percentage', models.IntegerField(help_text="He percentage (e.g., '79%')", validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('pressure', models.IntegerField(help_text="Cylinder pressure in PSI or BARs (e.g., '3000')", validators=[django.core.validators.MinValueValidator(0)])),
                ('unit_system', models.CharField(choices=[('metric', 'Metric'), ('imperial', 'Imperial')], help_text='Cylinder pressure unit Imperial (PSI) or Metric (BAR)', max_length=10)),
                ('use_anode', models.BooleanField(default=False)),
                ('last_visual_inspection_date', models.DateField(blank=True, null=True)),
                ('last_hydrostatic_test_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('functional', 'Functional'), ('needs_service', 'Needs Service'), ('broken', 'Broken'), ('lost', 'Lost'), ('abandoned', 'Abandoned')], default='functional', max_length=20)),
                ('created_by', models.EmailField(help_text='User who created the cylinder fleet.', max_length=254)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('fleet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cylinders', to='gis.cylinderfleet')),
            ],
            options={
                'ordering': ['-modified_date'],
            },
        ),
        migrations.CreateModel(
            name='CylinderFleetUserPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(choices=[(1, 'READ_ONLY'), (2, 'READ_AND_WRITE'), (3, 'ADMIN')], default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('cylinder_fleet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_permissions', to='gis.cylinderfleet')),
                ('deactivated_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cylinderfleet_permissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cylinder Fleet - User Permission',
                'verbose_name_plural': 'Cylinder Fleet - User Permissions',
            },
        ),
        migrations.CreateModel(
            name='CylinderInstall',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('latitude', models.DecimalField(decimal_places=7, help_text='Station latitude coordinate', max_digits=10, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)])),
                ('longitude', models.DecimalField(decimal_places=7, help_text='Station longitude coordinate', max_digits=10, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)])),
                ('notes', models.TextField(blank=True, default='', help_text='Optional notes for the cylinder install')),
                ('location_name', models.CharField(blank=True, help_text='Name of the location where the cylinder is installed', max_length=255)),
                ('distance_from_entry', models.IntegerField(blank=True, default=None, help_text='Distance from the entry of the location', null=True)),
                ('unit_system', models.CharField(choices=[('metric', 'Metric'), ('imperial', 'Imperial')], default='metric', help_text='Distance unit. Imperial: Feet, Metric: Meters', max_length=10)),
                ('install_date', models.DateField()),
                ('install_user', models.EmailField(help_text='User who installed the cylinder.', max_length=254)),
                ('uninstall_date', models.DateField(blank=True, default=None, null=True)),
                ('uninstall_user', models.EmailField(blank=True, default=None, help_text='User who retrieved the cylinder.', max_length=254, null=True)),
                ('status', models.CharField(choices=[('installed', 'Installed'), ('retrieved', 'Retrieved'), ('lost', 'Lost'), ('abandoned', 'Abandoned')], default='installed', max_length=20)),
                ('created_by', models.EmailField(help_text='User who created the cylinder fleet.', max_length=254)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('cylinder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installs', to='gis.cylinder')),
                ('project', models.ForeignKey(help_text='Project where the cylinder is installed', on_delete=django.db.models.deletion.CASCADE, related_name='cylinder_installs', to='surveys.project')),
            ],
            options={
                'verbose_name': 'Cylinder Install',
                'verbose_name_plural': 'Cylinder Installs',
                'ordering': ['-modified_date'],
            },
        ),
        migrations.CreateModel(
            name='CylinderPressureCheck',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user', models.EmailField(blank=True, help_text='User who did the pressure check.', max_length=254)),
                ('notes', models.TextField(blank=True, default='', help_text='Optional notes for the cylinder pressure check')),
                ('pressure', models.IntegerField(help_text="Cylinder pressure in PSI or BARs (e.g., '3000')", validators=[django.core.validators.MinValueValidator(0)])),
                ('unit_system', models.CharField(choices=[('metric', 'Metric'), ('imperial', 'Imperial')], help_text='Cylinder pressure unit Imperial (PSI) or Metric (BAR)', max_length=10)),
                ('check_date', models.DateField()),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('install', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pressure_checks', to='gis.cylinderinstall')),
            ],
        ),
        migrations.AddIndex(
            model_name='cylinder',
            index=models.Index(fields=['fleet'], name='gis_cylinde_fleet_i_afa571_idx'),
        ),
        migrations.AddIndex(
            model_name='cylinder',
            index=models.Index(fields=['status'], name='gis_cylinde_status_b876ad_idx'),
        ),
        migrations.AddIndex(
            model_name='cylinder',
            index=models.Index(fields=['fleet', 'status'], name='gis_cylinde_fleet_i_9889d7_idx'),
        ),
        migrations.AddConstraint(
            model_name='cylinder',
            constraint=models.CheckConstraint(condition=models.Q(('o2_percentage__lte', django.db.models.expressions.CombinedExpression(models.Value(100), '-', models.F('he_percentage')))), name='o2_he_sum_lte_100'),
        ),
        migrations.AddConstraint(
            model_name='cylinder',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('pressure__lte', 400), ('unit_system', 'metric')), models.Q(('pressure__lte', 5000), ('unit_system', 'imperial')), _connector='OR'), name='pressure_matches_unit_system'),
        ),
        migrations.AddIndex(
            model_name='cylinderfleetuserpermission',
            index=models.Index(fields=['user', 'is_active'], name='gis_cylinde_user_id_7eac6b_idx'),
        ),
        migrations.AddIndex(
            model_name='cylinderfleetuserpermission',
            index=models.Index(fields=['cylinder_fleet', 'is_active'], name='gis_cylinde_cylinde_854768_idx'),
        ),
        migrations.AddIndex(
            model_name='cylinderfleetuserpermission',
            index=models.Index(fields=['user', 'cylinder_fleet', 'is_active'], name='gis_cylinde_user_id_174a98_idx'),
        ),
        migrations.AddConstraint(
            model_name='cylinderfleetuserpermission',
            constraint=models.UniqueConstraint(fields=('user', 'cylinder_fleet'), name='unique_user_fleet_permission'),
        ),
        migrations.AddIndex(
            model_name='cylinderinstall',
            index=models.Index(fields=['cylinder'], name='gis_cylinde_cylinde_527f54_idx'),
        ),
        migrations.AddIndex(
            model_name='cylinderinstall',
            index=models.Index(fields=['latitude', 'longitude'], name='gis_cylinde_latitud_c15ac3_idx'),
        ),
        migrations.AddIndex(
            model_name='cylinderinstall',
            index=models.Index(fields=['cylinder', 'status'], name='gis_cylinde_cylinde_e8f271_idx'),
        ),
        migrations.AddConstraint(
            model_name='cylinderinstall',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(models.Q(('status', 'installed'), _negated=True), ('uninstall_date__isnull', False), ('uninstall_user__isnull', False)), models.Q(('status', 'installed'), ('uninstall_date__isnull', True), ('uninstall_user__isnull', True)), _connector='OR'), name='cylinder_uninstall_fields_match_is_installed'),
        ),
        migrations.AddConstraint(
            model_name='cylinderinstall',
            constraint=models.CheckConstraint(condition=models.Q(('uninstall_date__isnull', True), ('install_date__lte', models.F('uninstall_date')), _connector='OR'), name='cylinder_install_before_or_equal_retrieval'),
        ),
        migrations.AddConstraint(
            model_name='cylinderinstall',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'installed')), fields=('cylinder',), name='gis_cylinderinstall_installed_per_cylinder_unique'),
        ),
    ]
