# Generated by Django 6.0.1 on 2026-01-23 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gis', '0029_cylinderfleet_cylinder_cylinderfleetuserpermission_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subsurfacestation',
            name='type',
            field=models.CharField(
                choices=[('artifact', 'Artifact'), ('biology', 'Biology'), ('bone', 'Bone'), ('science', 'Science')], 
                default='science', 
                help_text='Type of SubSurfaceStation', 
                max_length=10
            ),
            preserve_default=False,
        ),
    ]
