# Generated by Django 6.0.1 on 2026-01-26 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gis', '0030_subsurfacestation_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subsurfacestation',
            name='type',
            field=models.CharField(choices=[('artifact', 'Artifact'), ('biology', 'Biology'), ('bone', 'Bone'), ('geology', 'Geology'), ('science', 'Science')], help_text='Type of SubSurfaceStation', max_length=10),
        ),
    ]
