# Generated by Django 6.0.1 on 2026-01-27 15:47

from django.db import migrations, models


def forwards_convert_science_to_sensor(apps, schema_editor):
    SubSurfaceStation = apps.get_model('gis', 'SubSurfaceStation')
    SubSurfaceStation.objects.filter(type='science').update(type='sensor')


def backwards_convert_sensor_to_science(apps, schema_editor):
    SubSurfaceStation = apps.get_model('gis', 'SubSurfaceStation')
    SubSurfaceStation.objects.filter(type='sensor').update(type='science')


class Migration(migrations.Migration):

    dependencies = [
        ('gis', '0031_alter_subsurfacestation_type'),
    ]

    operations = [
        # Adding the value "sensor"
        migrations.AlterField(
            model_name='subsurfacestation',
            name='type',
            field=models.CharField(
                choices=[('artifact', 'Artifact'), ('biology', 'Biology'), ('bone', 'Bone'), ('geology', 'Geology'), ('science', 'Science'), ('sensor', 'Sensor')], 
                help_text='Type of SubSurfaceStation', 
                max_length=10
            ),
        ),
        # Updating the DB values: `science => sensor`
        migrations.RunPython(
            forwards_convert_science_to_sensor,
            backwards_convert_sensor_to_science,
        ),
        # Removing the value "science"
        migrations.AlterField(
            model_name='subsurfacestation',
            name='type',
            field=models.CharField(
                choices=[('artifact', 'Artifact'), ('biology', 'Biology'), ('bone', 'Bone'), ('geology', 'Geology'), ('sensor', 'Sensor')], 
                help_text='Type of SubSurfaceStation', 
                max_length=10
            ),
        ),
    ]#
