# Generated by Django 6.0.1 on 2026-01-30 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gis', '0032_alter_subsurfacestation_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='gisview',
            name='allow_precise_zoom',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
