# Generated by Django 6.0.2 on 2026-02-06 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gis', '0033_gisview_allow_precise_zoom'),
    ]

    operations = [
        migrations.AddField(
            model_name='cylinder',
            name='manufactured_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gisview',
            name='allow_precise_zoom',
            field=models.BooleanField(help_text='If True, allows users to zoom to the precise location of the cave'),
        ),
    ]
