# Generated by Django 6.0.3 on 2026-04-09 05:45

import django.core.validators
import speleodb.common.enums
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gis', '0035_gpstrack_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gpstrack',
            name='color',
            field=models.CharField(default=speleodb.common.enums.ColorPalette.random_color, help_text='Hex color code for map rendering (e.g. #377eb8)', max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9a-fA-F]{6}$', 'Must be a #RRGGBB hex color')]),
        ),
    ]
