# Generated by Codex on 2026-04-24

import uuid

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations
from django.db import models

import speleodb.common.enums
import speleodb.gis.models.utils

_ADMIN_PERMISSION_LEVEL = 3
_PERSONAL_COLLECTION_COLOR = "#ffffff"


def backfill_landmark_personal_collections(apps, schema_editor):  # type: ignore[no-untyped-def]
    landmark_model = apps.get_model("gis", "Landmark")
    collection_model = apps.get_model("gis", "LandmarkCollection")
    permission_model = apps.get_model("gis", "LandmarkCollectionUserPermission")

    for landmark in landmark_model.objects.select_related("user", "collection").all():
        creator_email = landmark.user.email
        landmark.created_by = creator_email

        if landmark.collection_id is None:
            collection, _ = collection_model.objects.get_or_create(
                collection_type="PERSONAL",
                personal_owner_id=landmark.user_id,
                defaults={
                    "name": "Personal Landmarks",
                    "description": "",
                    "color": _PERSONAL_COLLECTION_COLOR,
                    "created_by": creator_email,
                    "is_active": True,
                },
            )
            permission, _ = permission_model.objects.get_or_create(
                user_id=landmark.user_id,
                collection_id=collection.id,
                defaults={"level": _ADMIN_PERMISSION_LEVEL},
            )
            if (
                not permission.is_active
                or permission.level != _ADMIN_PERMISSION_LEVEL
            ):
                permission.is_active = True
                permission.deactivated_by_id = None
                permission.level = _ADMIN_PERMISSION_LEVEL
                permission.save(
                    update_fields=[
                        "is_active",
                        "deactivated_by",
                        "level",
                        "modified_date",
                    ]
                )
            landmark.collection = collection

        landmark.save(update_fields=["created_by", "collection", "modified_date"])


def restore_landmark_users(apps, schema_editor):  # type: ignore[no-untyped-def]
    landmark_model = apps.get_model("gis", "Landmark")
    permission_model = apps.get_model("gis", "LandmarkCollectionUserPermission")
    user_app_label, user_model_name = settings.AUTH_USER_MODEL.split(".")
    user_model = apps.get_model(user_app_label, user_model_name)

    used_coordinate_keys = set()
    landmarks_to_delete = []

    for landmark in landmark_model.objects.select_related("collection").order_by(
        "creation_date",
        "id",
    ):
        candidate_user_ids = []
        collection = landmark.collection
        if collection.personal_owner_id is not None:
            candidate_user_ids.append(collection.personal_owner_id)

        candidate_user_ids.extend(
            permission_model.objects.filter(
                collection_id=landmark.collection_id,
                level=_ADMIN_PERMISSION_LEVEL,
                is_active=True,
            )
            .order_by("id")
            .values_list("user_id", flat=True)
        )
        candidate_user_ids.extend(
            permission_model.objects.filter(
                collection_id=landmark.collection_id,
                level=_ADMIN_PERMISSION_LEVEL,
            )
            .order_by("id")
            .values_list("user_id", flat=True)
        )
        candidate_user_ids.extend(
            permission_model.objects.filter(
                collection_id=landmark.collection_id,
                is_active=True,
            )
            .order_by("id")
            .values_list("user_id", flat=True)
        )
        candidate_user_ids.extend(
            permission_model.objects.filter(
                collection_id=landmark.collection_id,
            )
            .order_by("id")
            .values_list("user_id", flat=True)
        )

        creator_user_id = (
            user_model.objects.filter(email=landmark.created_by)
            .values_list("id", flat=True)
            .first()
        )
        if creator_user_id is not None:
            candidate_user_ids.append(creator_user_id)

        fallback_user_id = user_model.objects.order_by("id").values_list(
            "id",
            flat=True,
        ).first()
        if fallback_user_id is not None:
            candidate_user_ids.append(fallback_user_id)

        selected_user_id = None
        for candidate_user_id in dict.fromkeys(candidate_user_ids):
            coordinate_key = (
                candidate_user_id,
                landmark.latitude,
                landmark.longitude,
            )
            if coordinate_key not in used_coordinate_keys:
                selected_user_id = candidate_user_id
                used_coordinate_keys.add(coordinate_key)
                break

        if selected_user_id is None:
            landmarks_to_delete.append(landmark.id)
            continue

        landmark.user_id = selected_user_id
        landmark.save(update_fields=["user"])

    if landmarks_to_delete:
        landmark_model.objects.filter(id__in=landmarks_to_delete).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("gis", "0036_alter_gpstrack_color"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LandmarkCollection",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Landmark collection name",
                        max_length=100,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Optional description of the landmark collection",
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        default=speleodb.common.enums.ColorPalette.random_color,
                        help_text="Hex color code for map rendering (e.g. #377eb8)",
                        max_length=7,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^#[0-9a-fA-F]{6}$",
                                "Must be a #RRGGBB hex color",
                            )
                        ],
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "collection_type",
                    models.CharField(
                        choices=[
                            ("PERSONAL", "Personal"),
                            ("SHARED", "Shared"),
                        ],
                        default="SHARED",
                        max_length=16,
                    ),
                ),
                (
                    "personal_owner",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="personal_landmark_collections",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "gis_token",
                    models.CharField(
                        default=speleodb.gis.models.utils.generate_random_token,
                        max_length=40,
                        unique=True,
                        verbose_name="GIS Token",
                    ),
                ),
                (
                    "created_by",
                    models.EmailField(
                        help_text="User who created the landmark collection.",
                        max_length=254,
                    ),
                ),
                ("creation_date", models.DateTimeField(auto_now_add=True)),
                ("modified_date", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Landmark Collection",
                "verbose_name_plural": "Landmark Collections",
                "ordering": ["name"],
                "indexes": [
                    models.Index(fields=["is_active"], name="gis_lc_active_idx"),
                    models.Index(fields=["created_by"], name="gis_lc_created_by_idx"),
                    models.Index(
                        fields=["collection_type", "is_active"],
                        name="gis_lc_type_active_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("collection_type", "PERSONAL")),
                        fields=("personal_owner",),
                        name="gis_lc_one_personal_per_user",
                    ),
                    models.CheckConstraint(
                        condition=(
                            models.Q(
                                ("collection_type", "PERSONAL"),
                                ("personal_owner__isnull", False),
                            )
                            | models.Q(
                                ("collection_type", "SHARED"),
                                ("personal_owner__isnull", True),
                            )
                        ),
                        name="gis_lc_owner_matches_type",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="LandmarkCollectionUserPermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "level",
                    models.IntegerField(
                        choices=[
                            (1, "READ_ONLY"),
                            (2, "READ_AND_WRITE"),
                            (3, "ADMIN"),
                        ],
                        default=1,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "creation_date",
                    models.DateTimeField(auto_now_add=True, editable=False),
                ),
                (
                    "modified_date",
                    models.DateTimeField(auto_now=True, editable=False),
                ),
                (
                    "collection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="permissions",
                        to="gis.landmarkcollection",
                    ),
                ),
                (
                    "deactivated_by",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="landmark_collection_permissions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Landmark Collection - User Permission",
                "verbose_name_plural": "Landmark Collection - User Permissions",
                "indexes": [
                    models.Index(
                        fields=["user", "is_active"], name="gis_lcup_user_active_idx"
                    ),
                    models.Index(
                        fields=["collection", "is_active"],
                        name="gis_lcup_coll_active_idx",
                    ),
                    models.Index(
                        fields=["user", "collection", "is_active"],
                        name="gis_lcup_user_coll_act_idx",
                    ),
                ],
            },
        ),
        migrations.AddField(
            model_name="landmark",
            name="collection",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="landmarks",
                to="gis.landmarkcollection",
            ),
        ),
        migrations.AddField(
            model_name="landmark",
            name="created_by",
            field=models.EmailField(
                blank=True,
                help_text="User who created the landmark.",
                max_length=254,
                null=True,
            ),
        ),
        migrations.AddIndex(
            model_name="landmark",
            index=models.Index(
                fields=["collection"], name="gis_landmark_collection_idx"
            ),
        ),
        migrations.RemoveConstraint(
            model_name="landmark",
            name="gis_landmark_landmark_per_user_unique",
        ),
        migrations.RemoveIndex(
            model_name="landmark",
            name="gis_landmar_user_id_9f3bfc_idx",
        ),
        migrations.RunPython(
            backfill_landmark_personal_collections,
            migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name="landmark",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="landmarks",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.RunPython(
            migrations.RunPython.noop,
            restore_landmark_users,
        ),
        migrations.RemoveField(
            model_name="landmark",
            name="user",
        ),
        migrations.AlterField(
            model_name="landmark",
            name="collection",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="landmarks",
                to="gis.landmarkcollection",
            ),
        ),
        migrations.AlterField(
            model_name="landmark",
            name="created_by",
            field=models.EmailField(
                help_text="User who created the landmark.",
                max_length=254,
            ),
        ),
        migrations.AddConstraint(
            model_name="landmark",
            constraint=models.UniqueConstraint(
                fields=("collection", "latitude", "longitude"),
                name="gis_landmark_collection_coordinate_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="landmarkcollectionuserpermission",
            constraint=models.UniqueConstraint(
                fields=("user", "collection"),
                name="gis_lcup_user_collection_perm_unique",
            ),
        ),
    ]
