# Generated by Django 6.0.4 on 2026-08-09

from __future__ import annotations

from typing import Any

import django.db.models.deletion
from django.conf import settings
from django.db import migrations
from django.db import models
from django.utils import timezone


def backfill_gps_track_owner_permissions(
    apps: Any,
    schema_editor: Any,
) -> None:
    """Give every existing GPS Track owner an active ADMIN permission."""
    gps_track_model: type[Any] = apps.get_model("gis", "GPSTrack")
    permission_model: type[Any] = apps.get_model("gis", "GPSTrackUserPermission")
    permissions: list[Any] = []
    batch_size = 1000
    timestamp = timezone.now()

    for gps_track in gps_track_model.objects.only("id", "user_id").iterator(
        chunk_size=batch_size
    ):
        permissions.append(
            permission_model(
                user_id=gps_track.user_id,
                gps_track_id=gps_track.id,
                level=3,
                is_active=True,
                creation_date=timestamp,
                modified_date=timestamp,
            )
        )
        if len(permissions) == batch_size:
            permission_model.objects.bulk_create(
                permissions,
                batch_size=batch_size,
            )
            permissions.clear()

    if permissions:
        permission_model.objects.bulk_create(
            permissions,
            batch_size=batch_size,
        )


class Migration(migrations.Migration):
    dependencies = [
        ("gis", "0037_landmark_collections"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="gpstrack",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name="GPSTrackUserPermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "level",
                    models.IntegerField(
                        choices=[
                            (1, "READ_ONLY"),
                            (2, "READ_AND_WRITE"),
                            (3, "ADMIN"),
                        ],
                        default=1,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "creation_date",
                    models.DateTimeField(auto_now_add=True, editable=False),
                ),
                (
                    "modified_date",
                    models.DateTimeField(auto_now=True, editable=False),
                ),
                (
                    "deactivated_by",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "gps_track",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="permissions",
                        to="gis.gpstrack",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gps_track_permissions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "GPS Track - User Permission",
                "verbose_name_plural": "GPS Track - User Permissions",
                "indexes": [
                    models.Index(
                        fields=["user", "is_active"],
                        name="gis_gptup_user_active_idx",
                    ),
                    models.Index(
                        fields=["gps_track", "is_active"],
                        name="gis_gptup_track_active_idx",
                    ),
                    models.Index(
                        fields=["user", "gps_track", "is_active"],
                        name="gis_gptup_user_track_act_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "gps_track"),
                        name="gis_gptup_user_track_perm_uniq",
                    ),
                ],
            },
        ),
        migrations.RemoveConstraint(
            model_name="gpstrack",
            name="gis_gpstrack_gps_track_per_user_unique",
        ),
        migrations.AddIndex(
            model_name="gpstrack",
            index=models.Index(
                fields=["is_active"],
                name="gis_gpst_active_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="gpstrack",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True)),
                fields=("sha256_hash", "user"),
                name="gis_gpst_active_user_hash_uniq",
            ),
        ),
        migrations.RunPython(
            backfill_gps_track_owner_permissions,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
