# Generated by Django 6.0.8 on 2026-09-01 18:12

from django.db import migrations, models

import django.core.validators
import django.db.models.deletion
import functools
import speleodb.common.enums
import speleodb.gis.models.gis_layer
import speleodb.utils.s3_storages
import uuid
from django.conf import settings
from django.db import migrations, models 


def copy_user_email(apps, schema_editor):
    GPSTrack = apps.get_model('gis', 'GPSTrack')
    User = apps.get_model('users', 'User')

    for obj in GPSTrack.objects.all():
        # Check if FK exists
        if getattr(obj, "user_id", None) is None:
            raise ValueError(
                f"Cannot migrate GPSTrack id={obj.pk}: user FK is null"
            )

        # Check if the referenced User exists
        user = User.objects.filter(pk=obj.user_id).first()
        if not user:
            raise ValueError(
                f"Cannot migrate GPSTrack id={obj.pk}: User with id={obj.user_id} does not exist"
            )

        # Copy email
        obj.created_by_email = user.email
        obj.save(update_fields=['created_by_email'])


def copy_user_email_reverse(apps, schema_editor):
    GPSTrack = apps.get_model('gis', 'GPSTrack')
    User = apps.get_model('users', 'User')

    for obj in GPSTrack.objects.all():
        if obj.created_by_email:  # this is now the email string
            if user := User.objects.filter(email=obj.created_by_email).first():
                obj.created_by_id = user.id
                obj.save(update_fields=['created_by_id'])



class Migration(migrations.Migration):

    dependencies = [
        ('gis', '0038_gpstrack_sharing'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # 1. Cleanup all data & references
        migrations.RemoveConstraint(
            model_name='gpstrack',
            name='gis_gpst_active_user_hash_uniq',
        ),
        migrations.RemoveIndex(
            model_name='gpstrack',
            name='gis_gpstrac_user_id_7dba81_idx',
        ),
        migrations.RemoveIndex(
            model_name='gpstrack',
            name='gis_gpstrac_sha256__b30baf_idx',
        ),
        migrations.RemoveField(
            model_name='gpstrack',
            name='sha256_hash',
        ),

        # 2. Add temporary field to hold emails (nullable at first)
        migrations.AddField(
            model_name='gpstrack',
            name='created_by_email',
            field=models.EmailField(
                help_text='User who created or submitted the entry.',
                max_length=254,
                null=True,
            ),
        ),

        # 3. Copy data from FK to email
        migrations.RunPython(
            copy_user_email,
            reverse_code=copy_user_email_reverse
        ),

        # 4. Ensure no NULLs remain before removing FK
        migrations.AlterField(
            model_name='gpstrack',
            name='created_by_email',
            field=models.EmailField(
                help_text='User who created or submitted the entry.',
                max_length=254,
                null=False,
            ),
        ),

        # 5. Remove old FK field
        migrations.RemoveField(
            model_name='gpstrack',
            name='user',
        ),

        # 6. Rename new email field to original name
        migrations.RenameField(
            model_name='gpstrack',
            old_name='created_by_email',
            new_name='created_by',
        )
    ]
