# Generated by Django 6.0.8 on 2026-09-01 19:15

import django.core.validators
import django.db.models.deletion
import functools
import speleodb.common.enums
import speleodb.gis.models.gis_layer
import speleodb.utils.s3_storages
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gis', '0039_gpstrack_created_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GISLayer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='GIS Layer name', max_length=255)),
                ('description', models.TextField(blank=True, default='', max_length=2000, validators=[django.core.validators.MaxLengthValidator(2000)])),
                ('source_f', models.FileField(editable=False, storage=speleodb.utils.s3_storages.GISLayerStorage(), upload_to=functools.partial(speleodb.gis.models.gis_layer.get_gis_layer_upload_path, is_source=True), validators=[django.core.validators.FileExtensionValidator(('kml', 'kmz', 'json', 'geojson', 'topojson', 'zip'))])),
                ('data_f', models.FileField(editable=False, storage=speleodb.utils.s3_storages.GISLayerStorage(), upload_to=functools.partial(speleodb.gis.models.gis_layer.get_gis_layer_upload_path, is_source=False), validators=[django.core.validators.FileExtensionValidator(('json', 'geojson'))])),
                ('color', models.CharField(default=speleodb.common.enums.ColorPalette.random_color, help_text='Panel identity and fallback render color', max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9a-fA-F]{6}$', 'Must be a #RRGGBB hex color')])),
                ('created_by', models.EmailField(help_text='User who created or submitted the entry.', max_length=254)),
                ('is_active', models.BooleanField(default=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'GIS Layer',
                'verbose_name_plural': 'GIS Layers',
                'ordering': ['-modified_date'],
                'indexes': [models.Index(fields=['is_active'], name='gis_gisl_active_idx')],
            },
        ),
        migrations.CreateModel(
            name='GISLayerUserPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(choices=[(1, 'READ_ONLY'), (2, 'READ_AND_WRITE'), (3, 'ADMIN')], default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('deactivated_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
                ('gis_layer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='gis.gislayer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gis_layer_permissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'GIS Layer - User Permission',
                'verbose_name_plural': 'GIS Layer - User Permissions',
                'indexes': [models.Index(fields=['user', 'is_active'], name='gis_gislup_user_active_idx'), models.Index(fields=['gis_layer', 'is_active'], name='gis_gislup_layer_active_idx'), models.Index(fields=['user', 'gis_layer', 'is_active'], name='gis_gislup_user_layer_act_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'gis_layer'), name='gis_gislup_user_layer_uniq')],
            },
        ),
    ]
