# Generated by Django 6.0.8 on 2026-09-17 04:23

import django.core.validators
import django.db.models.deletion
import speleodb.common.enums
import speleodb.gis.geometry_validation
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gis', '0040_gislayer_gislayeruserpermission'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GISGeometry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='GIS Geometry name', max_length=255)),
                ('color', models.CharField(default=speleodb.common.enums.ColorPalette.random_color, max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9a-fA-F]{6}$', 'Must be a #RRGGBB hex color')])),
                ('created_by', models.EmailField(help_text='Email of the creator; provenance only.', max_length=254)),
                ('geojson', models.JSONField(help_text='A bare LineString or Polygon GeoJSON object using 2D longitude/latitude coordinates. The bounding box must not exceed 30 km², with a maximum of 100 vertices, to keep map editing and rendering responsive. Polygon closure does not count as a vertex.', validators=[speleodb.gis.geometry_validation.validate_gis_geometry])),
                ('revision', models.PositiveBigIntegerField(default=1, editable=False)),
                ('is_active', models.BooleanField(default=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'GIS Geometry',
                'verbose_name_plural': 'GIS Geometries',
                'ordering': ['-modified_date'],
                'indexes': [models.Index(fields=['is_active'], name='gis_gisg_active_idx')],
            },
        ),
        migrations.CreateModel(
            name='GISGeometryUserPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(choices=[(1, 'READ_ONLY'), (2, 'READ_AND_WRITE'), (3, 'ADMIN')], default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('deactivated_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
                ('gis_geometry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='gis.gisgeometry')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gis_geometry_permissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'GIS Geometry - User Permission',
                'verbose_name_plural': 'GIS Geometry - User Permissions',
                'indexes': [models.Index(fields=['user', 'is_active'], name='gis_gisgup_user_active_idx'), models.Index(fields=['gis_geometry', 'is_active'], name='gis_gisgup_geom_active_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'gis_geometry'), name='gis_gisgup_user_geom_uniq')],
            },
        ),
    ]
