# Config for Dependabot updates. See Documentation here:
# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  # Update GitHub actions in workflows
  - package-ecosystem: "github-actions"
    open-pull-requests-limit: 25
    directory: "/"
    target-branch: "dev"
    # Every weekday
    schedule:
      interval: "weekly"
    # on demand
    workflow_dispatch:

  # Enable version updates for Docker
  # We need to specify each Dockerfile in a separate entry because Dependabot doesn't
  # support wildcards or recursively checking subdirectories. Check this issue for updates:
  # https://github.com/dependabot/dependabot-core/issues/2178
  - package-ecosystem: "docker"
    open-pull-requests-limit: 25
    # Look for a `Dockerfile` in the `compose/local/django` directory
    directory: "compose/local/django/"
    target-branch: "dev"
    # Every weekday
    schedule:
      interval: "weekly"
    # Ignore minor version updates (3.10 -> 3.11) but update patch versions
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-major"
          - "version-update:semver-minor"

  - package-ecosystem: "docker"
    open-pull-requests-limit: 25
    # Look for a `Dockerfile` in the `compose/local/docs` directory
    directory: "compose/local/docs/"
    target-branch: "dev"
    # Every weekday
    schedule:
      interval: "weekly"
    # Ignore minor version updates (3.10 -> 3.11) but update patch versions
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-major"
          - "version-update:semver-minor"

  - package-ecosystem: "docker"
    open-pull-requests-limit: 25
    # Look for a `Dockerfile` in the `compose/production/aws` directory
    directory: "compose/production/aws/"
    target-branch: "dev"
    # Every weekday
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    open-pull-requests-limit: 25
    # Look for a `Dockerfile` in the `compose/production/django` directory
    directory: "compose/production/django/"
    target-branch: "dev"
    # Every weekday
    schedule:
      interval: "weekly"
    # Ignore minor version updates (3.10 -> 3.11) but update patch versions
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-major"
          - "version-update:semver-minor"

  - package-ecosystem: "docker"
    open-pull-requests-limit: 25
    # Look for a `Dockerfile` in the `compose/production/postgres` directory
    directory: "compose/production/postgres/"
    target-branch: "dev"
    # Every weekday
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    # Look for a `Dockerfile` in the `compose/production/traefik` directory
    directory: "compose/production/traefik/"
    target-branch: "dev"
    # Every weekday
    schedule:
      interval: "weekly"

  # Enable version updates for Python/Pip - Production
  - package-ecosystem: "pip"
    open-pull-requests-limit: 50
    # Look for a `requirements.txt` in the `root` directory
    # also 'setup.cfg', 'runtime.txt' and 'requirements/*.txt'
    directory: "/"
    target-branch: "dev"
    # Every weekday
    schedule:
      interval: "weekly"
