services:
  docs:
    image: speleodb_local_docs
    container_name: speleodb_local_docs
    build:
      context: .
      dockerfile: ./compose/local/docs/Dockerfile
    env_file:
      - ./.envs/.local/.django
    volumes:
      - ./docs:/docs:z
      - ./config:/app/config:z
      - ./speleodb:/app/speleodb:z
    ports:
      - "9000:9000"
    command: /start-docs
