version: "3"

volumes:
  speleodb_local_postgres_data: {}
  speleodb_local_postgres_data_backups: {}

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: speleodb_local_django
    container_name: speleodb_local_django
    depends_on:
      - postgres
      - redis
    volumes:
      - .:/app:z
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    ports:
      - "8000:8000"
    command: /start
    # command: sleep 600 && /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: speleodb_production_postgres
    container_name: speleodb_local_postgres
    volumes:
      - speleodb_local_postgres_data:/var/lib/postgresql/data
      - speleodb_local_postgres_data_backups:/backups
    env_file:
      - ./.envs/.local/.postgres
    ports:
      - "5432:5432"

  redis:
    image: docker.io/redis:6
    container_name: speleodb_local_redis

  celeryworker:
    <<: *django
    image: speleodb_local_celeryworker
    container_name: speleodb_local_celeryworker
    depends_on:
      - redis
      - postgres
    ports: []
    command: /start-celeryworker

  celerybeat:
    <<: *django
    image: speleodb_local_celerybeat
    container_name: speleodb_local_celerybeat
    depends_on:
      - redis
      - postgres
    ports: []
    command: /start-celerybeat

  flower:
    <<: *django
    image: speleodb_local_flower
    container_name: speleodb_local_flower
    ports:
      - "5555:5555"
    command: /start-flower
