# Generated by Django 5.2.8 on 2025-11-28 20:15

"""
A no-op migration to create proxy models for permissions admin.
See SQL generated by this migration for details:
`python manage.py sqlmigrate permissions 0001`

```
BEGIN;
--
-- Create proxy model ExperimentUserPermissionProxy
--
-- (no-op)
--
-- Create proxy model SensorFleetUserPermissionProxy
--
-- (no-op)
--
-- Create proxy model SurfaceMonitoringNetworkUserPermissionProxy
--
-- (no-op)
--
-- Create proxy model TeamProjectPermissionProxy
--
-- (no-op)
--
-- Create proxy model UserProjectPermissionProxy
--
-- (no-op)
COMMIT;
```
"""

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gis', '0017_surface_networks'),
        ('surveys', '0019_alter_format__format'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExperimentUserPermissionProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Experiment - User Permission',
                'verbose_name_plural': 'Experiment - User Permissions',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('gis.experimentuserpermission',),
        ),
        migrations.CreateModel(
            name='SensorFleetUserPermissionProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Sensor Fleet - User Permission',
                'verbose_name_plural': 'Sensor Fleet - User Permissions',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('gis.sensorfleetuserpermission',),
        ),
        migrations.CreateModel(
            name='SurfaceMonitoringNetworkUserPermissionProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Monitoring Network - User Permission',
                'verbose_name_plural': 'Monitoring Network - User Permissions',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('gis.surfacemonitoringnetworkuserpermission',),
        ),
        migrations.CreateModel(
            name='TeamProjectPermissionProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Project - Team Permission',
                'verbose_name_plural': 'Project - Team Permissions',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('surveys.teamprojectpermission',),
        ),
        migrations.CreateModel(
            name='UserProjectPermissionProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Project - User Permission',
                'verbose_name_plural': 'Project - User Permissions',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('surveys.userprojectpermission',),
        ),
    ]
