# Generated by Django 6.0.4 on 2026-04-26 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gis', '0037_landmark_collections'),
        ('permissions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CylinderFleetUserPermissionProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Cylinder Fleet - User Permission',
                'verbose_name_plural': 'Cylinder Fleet - User Permissions',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('gis.cylinderfleetuserpermission',),
        ),
        migrations.CreateModel(
            name='LandmarkCollectionUserPermissionProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Landmark Collection - User Permission',
                'verbose_name_plural': 'Landmark Collection - User Permissions',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('gis.landmarkcollectionuserpermission',),
        ),
    ]
