# Generated by Django 6.0.4 on 2026-08-09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("gis", "0038_gpstrack_sharing"),
        ("permissions", "0002_cylinderfleetuserpermissionproxy_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="GPSTrackUserPermissionProxy",
            fields=[],
            options={
                "verbose_name": "GPS Track - User Permission",
                "verbose_name_plural": "GPS Track - User Permissions",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("gis.gpstrackuserpermission",),
        ),
    ]
