# Generated by Django 6.0.8 on 2026-09-01 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gis', '0040_gislayer_gislayeruserpermission'),
        ('permissions', '0003_gpstrackuserpermissionproxy'),
    ]

    operations = [
        migrations.CreateModel(
            name='GISLayerUserPermissionProxy',
            fields=[
            ],
            options={
                'verbose_name': 'GIS Layer - User Permission',
                'verbose_name_plural': 'GIS Layer - User Permissions',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('gis.gislayeruserpermission',),
        ),
    ]
