# Generated by Django 6.0.8 on 2026-09-17 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gis', '0041_gis_geometry'),
        ('permissions', '0004_gislayeruserpermissionproxy'),
    ]

    operations = [
        migrations.CreateModel(
            name='GISGeometryUserPermissionProxy',
            fields=[
            ],
            options={
                'verbose_name': 'GIS Geometry - User Permission',
                'verbose_name_plural': 'GIS Geometry - User Permissions',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('gis.gisgeometryuserpermission',),
        ),
    ]
