# Generated by Django 5.2.4 on 2025-08-08 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial_squashed'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_beta_tester',
            field=models.BooleanField(default=False, help_text='Designates that this user has access to beta features before other users.'),
        ),
    ]
