# Generated by Django 5.2.8 on 2025-11-30 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0002_user_is_beta_tester'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['name'], 'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['country'], name='users_user_country_7f9bdb_idx'),
        ),
    ]
