# Generated by Django 5.0.6 on 2024-06-07 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_on_projects_updates',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='email_on_speleodb_updates',
            field=models.BooleanField(default=True),
        ),
    ]
