# Generated by Django 5.2.9 on 2025-12-06 19:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_index_optimizations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveyteammembership',
            name='deactivated_by',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='deactivated_memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='surveyteammembership',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='users.surveyteam'),
        ),
        migrations.AlterField(
            model_name='surveyteammembership',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='_team_memberships', to=settings.AUTH_USER_MODEL),
        ),
    ]