# Generated by Django 6.0.1 on 2026-01-16 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_related_fields_rename'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='surveyteammembership',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='surveyteammembership',
            constraint=models.UniqueConstraint(fields=('user', 'team'), name='users_surveyteammembership_user_team_membership_unique'),
        ),
    ]
