# Generated by Django 6.0.2 on 2026-02-23 05:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_unique_together_update'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_addr', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address')),
                ('user_agent', models.TextField(blank=True)),
                ('action', models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('signup', 'Signup'), ('password change', 'Password Changed'), ('password reset', 'Password Reset'), ('token refresh', 'Token Refresh')], max_length=20)),
                ('application', models.CharField(blank=True, choices=[('website', 'Website'), ('iOS', 'IOS'), ('android', 'Android'), ('ariane', 'Ariane'), ('compass', 'Compass'), ('unknown', 'Unknown')], default='', max_length=20)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_history', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'Account Event',
                'verbose_name_plural': 'Account Events',
                'ordering': ['-creation_date'],
                'indexes': [models.Index(fields=['user'], name='users_accou_user_id_f945bc_idx'), models.Index(fields=['ip_addr'], name='users_accou_ip_addr_e8573d_idx'), models.Index(fields=['action'], name='users_accou_action_8a0f73_idx'), models.Index(fields=['application'], name='users_accou_applica_b33a27_idx'), models.Index(fields=['creation_date'], name='users_accou_creatio_1a6085_idx')],
            },
        ),
    ]
