# Generated by Django 6.0.2 on 2026-02-24 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_accountevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountevent',
            name='application',
            field=models.CharField(blank=True, choices=[('android', 'Android'), ('ariane', 'Ariane'), ('compass', 'Compass'), ('iOS', 'iOS'), ('unittest', 'Unittest'), ('website', 'Website'), ('unknown', 'Unknown')], default='', max_length=20),
        ),
    ]
