# Generated by Django 6.0.6 on 2026-06-14 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_accountevent_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='has_api_doc_access',
            field=models.BooleanField(
                db_default=False,
                default=False,
                help_text=(
                    "Designates that this user can see API Docs and API Schema "
                    "links in the private menu."
                ),
            ),
        ),
    ]
