# Generated by Django 5.2.4 on 2025-07-10 20:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_surveyteam_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveyteammembership',
            name='deactivated_by',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='rel_deactivated_memberships', to=settings.AUTH_USER_MODEL),
        ),
    ]
