# Generated by Django 5.2.4 on 2025-07-13 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_convert_surveyteam_to_uuid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='surveyteammembership',
            old_name='_role',
            new_name='role',
        ),
    ]
