import type { Mock, MockInstance } from 'vitest';
import type { DmpDoctorContext } from '../../ts-types/controllers/dmp-doctor.ts';
import type { SurveyToolAjaxCall, UploadToolDouble, SurveyTableDouble, ConfiguredSurveyOptions } from '../../ts-types/testing/vitest/survey-tools.ts';
let ajax: Mock<(options: SurveyToolAjaxCall) => unknown>;
let anchorClick: MockInstance<() => void>;
let revokeUrl: Mock<(url: string) => void>;
let objectUrl: Mock<(blob: Blob | MediaSource) => string>;
let writeText: Mock<(text: string) => Promise<void>>;
import { readFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { init as initialize } from './dmp-doctor.ts';
import { attachToolFileUpload } from '../../frontend_private/static/private/ts/forms/tool_file_upload.ts';
vi.mock('../../frontend_private/static/private/ts/forms/tool_file_upload.ts', () => ({ attachToolFileUpload: vi.fn() }));
function init(context?: unknown) { return initialize(context as DmpDoctorContext); }
const jquery = readFileSync(resolve('frontend_public/static/ts/vendors/jquery-3.7.1.js'), 'utf8');
beforeAll(() => { (0, eval)(jquery); });
let dropzone: UploadToolDouble;
beforeEach(() => {
    vi.clearAllMocks();
    dropzone = { getFile: vi.fn(() => new File(['survey'], 'survey.dmp')), reset: vi.fn(), setStatus: vi.fn() };
    vi.mocked(attachToolFileUpload).mockReturnValue(dropzone);
    ajax = vi.fn(() => ({}));
    vi.spyOn($, 'ajax').mockImplementation(ajax as unknown as JQueryStatic['ajax']);
    anchorClick = vi.spyOn(HTMLAnchorElement.prototype, 'click').mockImplementation(() => {});
    objectUrl = vi.fn(() => 'blob:survey');
    window.URL.createObjectURL = objectUrl;
    revokeUrl = vi.fn();
    window.URL.revokeObjectURL = revokeUrl;
    document.body.innerHTML = '<input id="surveyDate"><input id="surveyDateUncorrupt"><input id="fixDmpSwitch" type="checkbox"><input id="depthUnitSwitch" type="checkbox" checked><input id="reverseDirectionSwitch" type="checkbox"><input id="lengthScaling" value="100"><input id="compassOffset" value="0"><input id="depthOffset" value="0"><span id="depthUnitSuffix"></span><button class="tab-button" data-tab="uncorrupt"></button><button class="tab-button" data-tab="adjust"></button><div class="tab-content" id="tab-uncorrupt"></div><div class="tab-content" id="tab-adjust"></div><button id="resetFormBtn"></button><button id="downloadBtn"></button><div id="status"></div><div id="loading_spinner" style="display:none"></div><div id="modal_error" style="display:none"><span id="modal_error_txt"></span></div><input name="csrfmiddlewaretoken" value="csrf">';
});
afterEach(() => { $(window).off('load'); $('body').off('click'); vi.restoreAllMocks(); delete (window.URL as unknown as {createObjectURL?: unknown}).createObjectURL; delete (window.URL as unknown as {revokeObjectURL?: unknown}).revokeObjectURL; document.body.innerHTML = ''; });
it('initializes immediately with DMP upload restrictions, initial repair toggle and date bounds', () => {
    expect(init({ endpoint: '/doctor/' })).toBeUndefined();
    expect(vi.mocked(attachToolFileUpload).mock.calls[0]![0]).toMatchObject({ allowedExtensions: ['dmp'], actionButtonSelector: '#downloadBtn', readyMessage: 'File ready for conversion' });
    expect($('#fixDmpSwitch').prop('checked')).toBe(true);
    expect($('#surveyDate').attr('max')).toBe(new Date().toISOString().split('T')[0]);
});
it('does not reset the same tab, resets changed tabs without resetting file, and explicitly resets files', () => {
    init({});
    $('#compassOffset').val('45');
    $('[data-tab="uncorrupt"]').trigger('click');
    expect($('#compassOffset').val()).toBe('45');
    $('[data-tab="adjust"]').trigger('click');
    expect($('#compassOffset').val()).toBe('0');
    expect($('#fixDmpSwitch').prop('checked')).toBe(false);
    expect(dropzone.reset).not.toHaveBeenCalled();
    expect($('#status').text()).toBe('Tab changed - form reset');
    $('#resetFormBtn').trigger('click');
    expect(dropzone.reset).toHaveBeenCalledOnce();
    expect(dropzone.setStatus).toHaveBeenCalledWith('Form reset', '#94a3b8', 'normal');
});
it('stores and restores compass input when reversing direction and uses actual checkbox receivers', () => {
    init({});
    $('#compassOffset').val('45');
    $('#reverseDirectionSwitch').prop('checked', true).trigger('change');
    expect($('#compassOffset').val()).toBe('180');
    expect($('#compassOffset').prop('disabled')).toBe(true);
    $('#reverseDirectionSwitch').prop('checked', false).trigger('change');
    expect($('#compassOffset').val()).toBe('45');
    expect($('#compassOffset').prop('disabled')).toBe(false);
    $('#depthUnitSwitch').prop('checked', false).trigger('change');
    expect($('#depthUnitSuffix').text()).toBe('m');
});
it.each([['lengthScaling', '0', 'Shot Length Scaling must be at least 1%.'], ['compassOffset', '360', 'Compass Offset must be between -360 and 359.'], ['depthOffset', '1001', 'Depth Offset must be between -1000 and 1000.']])('blocks invalid %s values before transport', (id, value, message) => {
    init({ endpoint: '/doctor/' });
    $(`#${id}`).val(value).trigger('input');
    expect($(`#${id}`).hasClass('invalid')).toBe(true);
    $('#downloadBtn').trigger('click');
    expect($('#status').text()).toBe(message);
    expect(ajax).not.toHaveBeenCalled();
});
it('sends file and exact adjustment JSON with CSRF, then downloads and revokes the returned blob', () => {
    const file = new File(['survey'], 'original.dmp');
    dropzone.getFile.mockReturnValue(file);
    init({ endpoint: '/doctor/' });
    $('#lengthScaling').val('125');
    $('#surveyDateUncorrupt').val('2026-01-01');
    $('#depthUnitSwitch').prop('checked', false).trigger('change');
    $('#downloadBtn').trigger('click');
    const request = ajax.mock.calls[0]![0];
    expect(request).toMatchObject({ url: '/doctor/', method: 'POST', processData: false, contentType: false, cache: false });
    expect((request.data as FormData).get('file')).toBe(file);
    expect(JSON.parse((request.data as FormData).get('data') as string) as unknown).toEqual({ fix_dmp: true, survey_date: '2026-01-01', length_scaling: 1.25, compass_offset: 0, reverse_direction: false, depth_offset: 0, depth_offset_unit: 'meters' });
    const xhr = { setRequestHeader: vi.fn() };
    expect(request.beforeSend!(xhr)).toBe(true);
    expect(xhr.setRequestHeader).toHaveBeenCalledWith('X-CSRFToken', 'csrf');
    expect($('#downloadBtn').prop('disabled')).toBe(true);
    request.success('converted');
    expect((anchorClick.mock.contexts[0] as HTMLAnchorElement).download).toBe('survey.dmp');
    expect((objectUrl.mock.calls[0]![0] as Blob).type).toBe('application/octet-stream');
    expect(revokeUrl).toHaveBeenCalledWith('blob:survey');
    expect($('a').length).toBe(0);
    expect($('#downloadBtn').prop('disabled')).toBe(false);
    expect($('#status').text()).toBe('Download successful!');
});
it('shows missing file and escaped response errors, preferring JSON error over detail', () => {
    init({});
    dropzone.getFile.mockReturnValueOnce(null);
    $('#downloadBtn').trigger('click');
    expect(dropzone.setStatus).toHaveBeenCalledWith('Please select a DMP file first.', 'red', 'bold');
    $('#downloadBtn').trigger('click');
    ajax.mock.calls[0]![0].error({ responseJSON: { error: '<unsafe>', detail: 'ignored' } }, 'error', 'fallback');
    expect($('#modal_error_txt').text()).toBe('<unsafe>');
    expect($('#modal_error_txt unsafe').length).toBe(0);
    expect($('#downloadBtn').prop('disabled')).toBe(false);
});
it('repeats handlers on reinitialization and propagates upload attachment errors', () => {
    init({});
    init({});
    $('#resetFormBtn').trigger('click');
    expect(dropzone.reset).toHaveBeenCalledTimes(2);
    const error = new Error('Upload failed');
    vi.mocked(attachToolFileUpload).mockImplementationOnce(() => { throw error; });
    expect(() => init({})).toThrow(error);
});
