# Generated by Django 4.2.11 on 2024-05-05 21:23

from django.db import migrations, models
import encrypted_model_fields.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Option',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('value', encrypted_model_fields.fields.EncryptedCharField(default='')),
            ],
        ),
    ]
