# Generated by Django 5.2.4 on 2025-07-22 16:04

import django.core.validators
import speleodb.utils.storages
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BoardMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(help_text='Full name of the person', max_length=200)),
                ('title', models.CharField(help_text='Professional title or role', max_length=200)),
                ('description', models.TextField(help_text="Biography or description of the person's involvement")),
                ('link_name', models.CharField(blank=True, default='', help_text="Display text for the link (e.g., 'LinkedIn', 'Personal Website')", max_length=100)),
                ('link_target', models.URLField(blank=True, default='', help_text="URL for the person's profile or website")),
                ('photo', models.ImageField(help_text='Photo of the person (JPEG, PNG, or WebP format)', storage=speleodb.utils.storages.PersonPhotoStorage(), upload_to='people/photos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])])),
                ('order', models.IntegerField(blank=True, help_text='Custom order for display (lower numbers appear first)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Board Member',
                'verbose_name_plural': 'Board of Directors',
                'ordering': ['order', 'full_name'],
            },
        ),
        migrations.CreateModel(
            name='ExplorerMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(help_text='Full name of the person', max_length=200)),
                ('title', models.CharField(help_text='Professional title or role', max_length=200)),
                ('description', models.TextField(help_text="Biography or description of the person's involvement")),
                ('link_name', models.CharField(blank=True, default='', help_text="Display text for the link (e.g., 'LinkedIn', 'Personal Website')", max_length=100)),
                ('link_target', models.URLField(blank=True, default='', help_text="URL for the person's profile or website")),
                ('photo', models.ImageField(help_text='Photo of the person (JPEG, PNG, or WebP format)', storage=speleodb.utils.storages.PersonPhotoStorage(), upload_to='people/photos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])])),
                ('order', models.IntegerField(blank=True, help_text='Custom order for display (lower numbers appear first)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Explorer Board Member',
                'verbose_name_plural': 'Explorer Advisory Board',
                'ordering': ['order', 'full_name'],
            },
        ),
        migrations.CreateModel(
            name='TechnicalMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(help_text='Full name of the person', max_length=200)),
                ('title', models.CharField(help_text='Professional title or role', max_length=200)),
                ('description', models.TextField(help_text="Biography or description of the person's involvement")),
                ('link_name', models.CharField(blank=True, default='', help_text="Display text for the link (e.g., 'LinkedIn', 'Personal Website')", max_length=100)),
                ('link_target', models.URLField(blank=True, default='', help_text="URL for the person's profile or website")),
                ('photo', models.ImageField(help_text='Photo of the person (JPEG, PNG, or WebP format)', storage=speleodb.utils.storages.PersonPhotoStorage(), upload_to='people/photos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])])),
                ('order', models.IntegerField(blank=True, help_text='Custom order for display (lower numbers appear first)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Technical Committee Member',
                'verbose_name_plural': 'Technical Steering Committee',
                'ordering': ['order', 'full_name'],
            },
        ),
        migrations.AlterModelOptions(
            name='boardmember',
            options={'ordering': [models.OrderBy(models.F('order'), nulls_last=True), 'full_name'], 'verbose_name': 'Board Member', 'verbose_name_plural': 'Board of Directors'},
        ),
        migrations.AlterModelOptions(
            name='explorermember',
            options={'ordering': [models.OrderBy(models.F('order'), nulls_last=True), 'full_name'], 'verbose_name': 'Explorer Board Member', 'verbose_name_plural': 'Explorer Advisory Board'},
        ),
        migrations.AlterModelOptions(
            name='technicalmember',
            options={'ordering': [models.OrderBy(models.F('order'), nulls_last=True), 'full_name'], 'verbose_name': 'Technical Committee Member', 'verbose_name_plural': 'Technical Steering Committee'},
        ),
    ]
