# Generated by Django 5.2.4 on 2025-08-08 21:45

import speleodb.utils.storages
import speleodb.utils.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend_public', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardmember',
            name='photo',
            field=models.ImageField(help_text='Photo of the person (JPEG, PNG, or WebP format)', storage=speleodb.utils.storages.PersonPhotoStorage(), upload_to='people/photos/', validators=[speleodb.utils.validators.ImageWithHeicSupportValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])]),
        ),
        migrations.AlterField(
            model_name='explorermember',
            name='photo',
            field=models.ImageField(help_text='Photo of the person (JPEG, PNG, or WebP format)', storage=speleodb.utils.storages.PersonPhotoStorage(), upload_to='people/photos/', validators=[speleodb.utils.validators.ImageWithHeicSupportValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])]),
        ),
        migrations.AlterField(
            model_name='technicalmember',
            name='photo',
            field=models.ImageField(help_text='Photo of the person (JPEG, PNG, or WebP format)', storage=speleodb.utils.storages.PersonPhotoStorage(), upload_to='people/photos/', validators=[speleodb.utils.validators.ImageWithHeicSupportValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])]),
        ),
    ]
