# Generated by Django 5.2.8 on 2025-11-20 14:54

import speleodb.utils.storages
import speleodb.utils.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend_public', '0002_alter_boardmember_photo_alter_explorermember_photo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScientificMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(help_text='Full name of the person', max_length=200)),
                ('title', models.CharField(help_text='Professional title or role', max_length=200)),
                ('description', models.TextField(help_text="Biography or description of the person's involvement")),
                ('link_name', models.CharField(blank=True, default='', help_text="Display text for the link (e.g., 'LinkedIn', 'Personal Website')", max_length=100)),
                ('link_target', models.URLField(blank=True, default='', help_text="URL for the person's profile or website")),
                ('photo', models.ImageField(help_text='Photo of the person (JPEG, PNG, or WebP format)', storage=speleodb.utils.storages.PersonPhotoStorage(), upload_to='people/photos/', validators=[speleodb.utils.validators.ImageWithHeicSupportValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])])),
                ('order', models.IntegerField(blank=True, help_text='Custom order for display (lower numbers appear first)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Scientific Board Member',
                'verbose_name_plural': 'Scientific Advisory Board',
                'ordering': [models.OrderBy(models.F('order'), nulls_last=True), 'full_name'],
            },
        ),
    ]
