# Generated by Django 6.0.2 on 2026-02-22 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend_public', '0003_scientificmember'),
    ]

    operations = [
        migrations.RenameField(
            model_name='boardmember',
            old_name='created_at',
            new_name='creation_date',
        ),
        migrations.RenameField(
            model_name='boardmember',
            old_name='updated_at',
            new_name='modified_date',
        ),
        migrations.RenameField(
            model_name='explorermember',
            old_name='created_at',
            new_name='creation_date',
        ),
        migrations.RenameField(
            model_name='explorermember',
            old_name='updated_at',
            new_name='modified_date',
        ),
        migrations.RenameField(
            model_name='scientificmember',
            old_name='created_at',
            new_name='creation_date',
        ),
        migrations.RenameField(
            model_name='scientificmember',
            old_name='updated_at',
            new_name='modified_date',
        ),
        migrations.RenameField(
            model_name='technicalmember',
            old_name='created_at',
            new_name='creation_date',
        ),
        migrations.RenameField(
            model_name='technicalmember',
            old_name='updated_at',
            new_name='modified_date',
        ),
    ]
