# Generated by Django 5.2.8 on 2025-11-17 04:33

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('surveys', '0014_project_is_active'),
    ]

    operations = []
