# Generated by Django 5.2.8 on 2025-11-30 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plugins', '0002_models_transfer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pluginrelease',
            options={'ordering': ['-creation_date'], 'verbose_name': 'Public Annoucement', 'verbose_name_plural': 'Public Annoucements'},
        ),
        migrations.AlterModelOptions(
            name='publicannoucement',
            options={'ordering': ['-creation_date'], 'verbose_name': 'Public Annoucement', 'verbose_name_plural': 'Public Annoucements'},
        ),
        migrations.AddField(
            model_name='pluginrelease',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is Active'),
        ),
        migrations.AddIndex(
            model_name='pluginrelease',
            index=models.Index(fields=['creation_date'], name='plugins_plu_creatio_0d4b07_idx'),
        ),
        migrations.AddIndex(
            model_name='pluginrelease',
            index=models.Index(fields=['is_active'], name='plugins_plu_is_acti_85c852_idx'),
        ),
        migrations.AddIndex(
            model_name='pluginrelease',
            index=models.Index(fields=['software'], name='plugins_plu_softwar_1a42d1_idx'),
        ),
        migrations.AddIndex(
            model_name='publicannoucement',
            index=models.Index(fields=['software'], name='plugins_pub_softwar_0cad05_idx'),
        ),
        migrations.AddIndex(
            model_name='publicannoucement',
            index=models.Index(fields=['version'], name='plugins_pub_version_fb67e2_idx'),
        ),
        migrations.AddIndex(
            model_name='publicannoucement',
            index=models.Index(fields=['is_active'], name='plugins_pub_is_acti_d9d4de_idx'),
        ),
        migrations.AddIndex(
            model_name='publicannoucement',
            index=models.Index(fields=['creation_date'], name='plugins_pub_creatio_a394db_idx'),
        ),
    ]
