# Generated by Django 5.2.9 on 2025-12-06 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plugins', '0003_model_optimizations'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pluginrelease',
            options={'ordering': ['-creation_date'], 'verbose_name': 'Plugin Release', 'verbose_name_plural': 'Plugin Releases'},
        ),
    ]
