# Generated by Django 5.0.6 on 2024-06-11 17:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0008_permission_creation_date_permission_is_active_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='mutex',
            old_name='heartbeat_dt',
            new_name='last_modified_dt',
        ),
        migrations.RemoveField(
            model_name='mutex',
            name='closing_dt',
        ),
        migrations.AddField(
            model_name='permission',
            name='deactivated_by',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='rel_deactivated_permissions', to=settings.AUTH_USER_MODEL),
        ),
    ]
