# Generated by Django 5.0.6 on 2024-06-19 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0011_alter_project_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mutex',
            old_name='creation_dt',
            new_name='creation_date',
        ),
        migrations.RenameField(
            model_name='mutex',
            old_name='last_modified_dt',
            new_name='modified_date',
        ),
    ]
