# Generated by Django 5.1.3 on 2024-12-03 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0014_alter_format__format'),
    ]

    operations = [
        migrations.AlterField(
            model_name='format',
            name='_format',
            field=models.IntegerField(choices=[(1000, 'OTHER'), (9998, 'AUTO'), (9999, 'DUMP'), (10, 'ARIANE_TML'), (11, 'ARIANE_TMLU'), (12, 'ARIANE_AGR'), (20, 'COMPASS_MAK'), (21, 'COMPASS_DAT'), (30, 'WALLS_SRV'), (31, 'WALLS_WPJ'), (40, 'STICKMAPS')], verbose_name='format'),
        ),
    ]
