# Generated by Django 5.1.4 on 2025-01-07 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0017_project_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='active_mutex',
        ),
    ]
