# Generated by Django 5.1.6 on 2025-03-06 04:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0019_project_latitude_longitude_must_both_me_null_not_null_simultaneously'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='mutex',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rel_mutexes', to=settings.AUTH_USER_MODEL),
        ),
    ]
