# Generated by Django 5.1.8 on 2025-05-25 20:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0020_alter_mutex_user'),
        ('users', '0003_alter_surveyteam_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Renaming Fields
        migrations.RenameField(
            model_name='teampermission',
            old_name='_level',
            new_name='level',
        ),
        migrations.RenameField(
            model_name='userpermission',
            old_name='_level',
            new_name='level',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='_visibility',
            new_name='visibility',
        ),
        # Altering Fields
        migrations.AlterField(
            model_name='teampermission',
            name='level',
            field=models.IntegerField(choices=[(0, 'READ_ONLY'), (1, 'READ_AND_WRITE'), (2, 'ADMIN')], default=0),
        ),
        migrations.AlterField(
            model_name='userpermission',
            name='level',
            field=models.IntegerField(choices=[(0, 'READ_ONLY'), (1, 'READ_AND_WRITE'), (2, 'ADMIN')], default=0),
        ),
        migrations.AddConstraint(
            model_name='teampermission',
            constraint=models.CheckConstraint(condition=models.Q(('level__in', [0, 1])), name='surveys_teampermission_level_is_valid'),
        ),
        migrations.AlterField(
            model_name='project',
            name='visibility',
            field=models.IntegerField(choices=[(0, 'PRIVATE'), (1, 'PUBLIC')], default=0),
        )
    ]
