# Generated by Django 5.2.3 on 2025-06-23 23:36

import django.core.validators
import speleodb.surveys.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0022_publicannoucement'),
    ]

    operations = [
        migrations.CreateModel(
            name='PluginRelease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plugin_version', speleodb.surveys.fields.VersionField(max_length=50, validators=[django.core.validators.RegexValidator(message='Enter a valid SemVer (e.g., 1.2.3) or CalVer (e.g., 2025.06.23)', regex='(^(?P<major>0|[1-9]\\d*)\\.(?P<minor>0|[1-9]\\d*)\\.(?P<patch>0|[1-9]\\d*)$)|(^(?P<year>2[0-9]{3})\\.(?P<month>1[0-2]|0?[1-9])(\\.(?P<day>3[0-1]|[1-2][0-9]|0?[1-9]))?$)')], verbose_name='Plugin version')),
                ('software', models.IntegerField(choices=[(0, 'WEB'), (1, 'ARIANE')])),
                ('software_version', speleodb.surveys.fields.VersionField(blank=True, default='', max_length=50, validators=[django.core.validators.RegexValidator(message='Enter a valid SemVer (e.g., 1.2.3) or CalVer (e.g., 2025.06.23)', regex='(^(?P<major>0|[1-9]\\d*)\\.(?P<minor>0|[1-9]\\d*)\\.(?P<patch>0|[1-9]\\d*)$)|(^(?P<year>2[0-9]{3})\\.(?P<month>1[0-2]|0?[1-9])(\\.(?P<day>3[0-1]|[1-2][0-9]|0?[1-9]))?$)')], verbose_name='Software version')),
                ('operating_system', models.IntegerField(choices=[(0, 'ANY'), (10, 'MACOS'), (11, 'MACOS_INTEL'), (12, 'MACOS_ARM'), (20, 'WINDOWS'), (21, 'WINDOWS_32'), (22, 'WINDOWS_64'), (30, 'LINUX'), (31, 'LINUX_32'), (32, 'LINUX_64')], default=0)),
                ('changelog', models.TextField()),
                ('sha256_hash', speleodb.surveys.fields.Sha256Field(blank=True, max_length=64, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Enter a valid sha256 value', regex='^[a-fA-F0-9]{64}$')], verbose_name='SHA256 Hash')),
                ('download_url', models.URLField(max_length=500)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
