# Generated by Django 5.2.3 on 2025-06-28 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0024_change_software_version_to_min_max'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='geojson',
            field=models.JSONField(blank=True, default=dict, help_text='GeoJSON data for this project. Only loaded when explicitly requested.'),
        ),
    ]
