# Generated by Django 5.2.3 on 2025-07-01 02:36

from django.conf import settings
from django.db import migrations, models


def shift_permission_levels_up(apps, schema_editor):
    """Shift all existing permission levels up by 1 to make room for WEB_VIEWER at 0."""
    UserPermission = apps.get_model('surveys', 'UserPermission')
    TeamPermission = apps.get_model('surveys', 'TeamPermission')
    
    # Shift UserPermission levels (do in reverse order to avoid conflicts)
    for level in [2, 1, 0]:  # ADMIN, READ_AND_WRITE, READ_ONLY
        UserPermission.objects.filter(level=level).update(level=level + 1)
    
    # Shift TeamPermission levels (do in reverse order to avoid conflicts)
    for level in [1, 0]:  # READ_AND_WRITE, READ_ONLY (no ADMIN for teams)
        TeamPermission.objects.filter(level=level).update(level=level + 1)


def shift_permission_levels_down(apps, schema_editor):
    """Reverse migration: shift all permission levels down by 1."""
    UserPermission = apps.get_model('surveys', 'UserPermission')
    TeamPermission = apps.get_model('surveys', 'TeamPermission')
    
    # Shift UserPermission levels (do in forward order to avoid conflicts)
    for level in [1, 2, 3]:  # READ_ONLY, READ_AND_WRITE, ADMIN
        UserPermission.objects.filter(level=level).update(level=level - 1)
    
    # Shift TeamPermission levels (do in forward order to avoid conflicts)
    for level in [1, 2]:  # READ_ONLY, READ_AND_WRITE
        TeamPermission.objects.filter(level=level).update(level=level - 1)


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0025_project_geojson'),
        ('users', '0003_alter_surveyteam_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='teampermission',
            name='surveys_teampermission_level_is_valid',
        ),
        # First, shift existing permission levels
        migrations.RunPython(shift_permission_levels_up, shift_permission_levels_down),
        migrations.AlterField(
            model_name='teampermission',
            name='level',
            field=models.IntegerField(choices=[(0, 'WEB_VIEWER'), (1, 'READ_ONLY'), (2, 'READ_AND_WRITE'), (3, 'ADMIN')], default=1),
        ),
        migrations.AlterField(
            model_name='userpermission',
            name='level',
            field=models.IntegerField(choices=[(0, 'WEB_VIEWER'), (1, 'READ_ONLY'), (2, 'READ_AND_WRITE'), (3, 'ADMIN')], default=1),
        ),
        migrations.AddConstraint(
            model_name='teampermission',
            constraint=models.CheckConstraint(condition=models.Q(('level__in', [0, 1, 2])), name='surveys_teampermission_level_is_valid'),
        ),
    ]
