# Generated by Django 5.2.4 on 2025-07-08 17:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0028_station_stationresource_pointofinterest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointofinterest',
            name='name',
            field=models.CharField(help_text='Point of Interest name', max_length=100),
        ),
        migrations.AddIndex(
            model_name='pointofinterest',
            index=models.Index(fields=['created_by'], name='surveys_poi_created_7c3dcc_idx'),
        ),
    ]
