# Generated by Django 5.2.4 on 2025-07-13 02:21

from django.db import migrations, models


def set_mutex_active_status(apps, schema_editor):
    Mutex = apps.get_model('surveys', 'Mutex')
    for mutex in Mutex.objects.all():
        mutex.is_active = mutex.closing_user is None
        mutex.save(update_fields=["is_active"])


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0033_alter_project_created_by_alter_station_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mutex',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is Active'),
        ),
        migrations.RunPython(set_mutex_active_status),  # Necessary to properly set mutex active status
       
    ]
