name: CI

# Enable Buildkit and let compose use it to speed up image building
env:
  DOCKER_BUILDKIT: 1
  COMPOSE_DOCKER_CLI_BUILD: 1

on:
  pull_request:
    branches: ["master", "main", "dev"]
    paths-ignore: ["docs/**"]

  push:
    branches: ["master", "main", "dev", "type-checking"]
    paths-ignore: ["docs/**"]

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  linter:
    runs-on: ubuntu-latest
    env:
      CELERY_BROKER_URL: "redis://localhost:6379/0"
      DATABASE_URL: "postgres://postgres:postgres@localhost:5432/postgres"
      # Dummy Key - Not Used
      DJANGO_SECRET_KEY: "s&=i@9h+)6bge)6!6vhbcx@=#^6nr73&7+6ep-xpbebhi5#)+_"
      # Dummy Key - Not Used
      GITLAB_GROUP_ID: "whatever"
      GITLAB_GROUP_NAME: "whatever"
      GITLAB_HOST_URL: "whatever"
      GITLAB_TOKEN: "whatever"
      AWS_ACCESS_KEY_ID: "whatever"
      AWS_SECRET_ACCESS_KEY: "whatever"
      AWS_S3_REGION_NAME: "whatever"
      AWS_STORAGE_BUCKET_NAME: "whatever"
      MAPBOX_API_TOKEN: "whatever"

    steps:
      - name: Checkout Code Repository
        uses: actions/checkout@v5

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "latest"
          python-version: "3.13"
          activate-environment: true
        env:
          UV_VENV_SEED: 1

      - name: Install Dependencies
        run: uv sync --extra local --frozen

      # Consider using pre-commit.ci for open source project
      - name: Run pre-commit
        uses: pre-commit/action@v3.0.1

  # With no caching at all the entire ci process takes 3m to complete!
  pytest:
    runs-on: ubuntu-latest

    services:
      redis:
        image: redis:6
        ports:
          - 6379:6379
      postgres:
        image: postgres:16
        ports:
          - 5432:5432
        env:
          POSTGRES_PASSWORD: postgres

    env:
      CELERY_BROKER_URL: "redis://localhost:6379/0"
      # postgres://user:password@host:port/database
      DATABASE_URL: "postgres://postgres:postgres@localhost:5432/postgres"

    steps:
      - name: Checkout Code Repository
        uses: actions/checkout@v5

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "latest"
          python-version: "3.13"
          activate-environment: true

      - name: Install Dependencies
        run: uv sync --extra local --frozen

      - name: Run Tests
        run: |
          python manage.py validate_templates --settings config.settings.test --ignore-app allauth
          pytest
        env:
          GITLAB_GROUP_ID: ${{ secrets.GITLAB_GROUP_ID }}
          GITLAB_GROUP_NAME: ${{ secrets.GITLAB_GROUP_NAME }}
          GITLAB_HOST_URL: ${{ secrets.GITLAB_HOST_URL }}
          GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_S3_REGION_NAME: ${{ secrets.AWS_S3_REGION_NAME }}
          AWS_STORAGE_BUCKET_NAME: ${{ secrets.AWS_STORAGE_BUCKET_NAME }}
          MAPBOX_API_TOKEN: ${{ secrets.MAPBOX_API_TOKEN }}
