name: Pre-commit auto-update

on:
  # every day at midnight
  schedule:
    - cron: "0 0 * * *"
  # on demand
  workflow_dispatch:

jobs:
  auto-update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
          cache: pip

      - name: AutoUpdate
        uses: browniebroke/pre-commit-autoupdate-action@main

      - name: Open PRs for changes
        uses: peter-evans/create-pull-request@v7
        if: always()
        with:
            token: ${{ secrets.GITHUB_TOKEN }}
            branch: update/pre-commit-hooks
            title: Update pre-commit hooks
            commit-message: "chore: update pre-commit hooks"
            body: Update versions of pre-commit hooks to latest version.
